import type { GameConfig } from "../../types";

export const aboutMeGames: GameConfig[] = [
  {
    id: "aboutme-body-quiz",
    zoneId: "about-me",
    type: "picture_quiz",
    title: "My Body Parts",
    description: "Can you name the parts of your body?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Point to the right body part!",
      questions: [
        {
          id: "q1",
          question: "Which part do you use to see things?",
          options: [
            { id: "eyes", label: "Eyes", emoji: "👀" },
            { id: "ears", label: "Ears", emoji: "👂" },
            { id: "nose", label: "Nose", emoji: "👃" },
            { id: "mouth", label: "Mouth", emoji: "👄" },
          ],
          correctId: "eyes",
          explanation: "Your eyes help you see all the beautiful colors around you!",
        },
        {
          id: "q2",
          question: "Which part do you use to hear sounds?",
          options: [
            { id: "hands", label: "Hands", emoji: "🤲" },
            { id: "feet", label: "Feet", emoji: "🦶" },
            { id: "ears", label: "Ears", emoji: "👂" },
            { id: "mouth", label: "Mouth", emoji: "👄" },
          ],
          correctId: "ears",
          explanation: "Your ears catch sounds like music, birds singing, and your friends talking!",
        },
        {
          id: "q3",
          question: "Which part do you use to smell a flower?",
          options: [
            { id: "nose", label: "Nose", emoji: "👃" },
            { id: "eyes", label: "Eyes", emoji: "👀" },
            { id: "hands", label: "Hands", emoji: "🤲" },
            { id: "tongue", label: "Tongue", emoji: "👅" },
          ],
          correctId: "nose",
          explanation: "Your nose helps you smell yummy food, flowers, and fresh air!",
        },
        {
          id: "q4",
          question: "How many fingers do you have on both hands?",
          options: [
            { id: "five", label: "Five", emoji: "5️⃣" },
            { id: "eight", label: "Eight", emoji: "8️⃣" },
            { id: "ten", label: "Ten", emoji: "🔟" },
            { id: "twelve", label: "Twelve", emoji: "1️⃣2️⃣" },
          ],
          correctId: "ten",
          explanation: "Five fingers on each hand makes ten fingers total!",
        },
      ],
    },
  },
  {
    id: "aboutme-senses-sort",
    zoneId: "about-me",
    type: "drag_sort",
    title: "My Five Senses",
    description: "Match each thing to the sense you use!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Which sense do you use for each thing?",
      categories: [
        { id: "see", label: "See (Eyes)", emoji: "👀" },
        { id: "hear", label: "Hear (Ears)", emoji: "👂" },
        { id: "smell", label: "Smell (Nose)", emoji: "👃" },
      ],
      items: [
        { id: "rainbow", label: "Rainbow", emoji: "🌈", category: "see" },
        { id: "music", label: "Music", emoji: "🎵", category: "hear" },
        { id: "flower", label: "Flower scent", emoji: "🌸", category: "smell" },
        { id: "painting", label: "Painting", emoji: "🖼️", category: "see" },
        { id: "thunder", label: "Thunder", emoji: "⛈️", category: "hear" },
        { id: "perfume", label: "Perfume", emoji: "🧴", category: "smell" },
      ],
    },
  },
  {
    id: "aboutme-feelings-match",
    zoneId: "about-me",
    type: "memory_match",
    title: "Feelings Match",
    description: "Match the feeling with its emoji!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Find matching pairs of feelings!",
      pairs: [
        { id: "happy", front: "Happy", emoji: "😊" },
        { id: "sad", front: "Sad", emoji: "😢" },
        { id: "angry", front: "Angry", emoji: "😠" },
        { id: "scared", front: "Scared", emoji: "😨" },
        { id: "excited", front: "Excited", emoji: "🤩" },
        { id: "sleepy", front: "Sleepy", emoji: "😴" },
      ],
    },
  },
  {
    id: "aboutme-odd-senses",
    zoneId: "about-me",
    type: "odd_one_out",
    title: "Odd Sense Out",
    description: "Find the item that doesn't belong!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "One of these doesn't belong with the others. Can you spot it?",
      rounds: [
        {
          id: "r1",
          category: "body parts",
          items: [
            { id: "eye", label: "Eye", emoji: "👁️" },
            { id: "ear", label: "Ear", emoji: "👂" },
            { id: "nose", label: "Nose", emoji: "👃" },
            { id: "shoe", label: "Shoe", emoji: "👟" },
          ],
          oddId: "shoe",
          explanation: "A shoe is something you wear — it's not a body part!",
        },
        {
          id: "r2",
          category: "feelings",
          items: [
            { id: "happy", label: "Happy", emoji: "😊" },
            { id: "sad", label: "Sad", emoji: "😢" },
            { id: "angry", label: "Angry", emoji: "😠" },
            { id: "apple", label: "Apple", emoji: "🍎" },
          ],
          oddId: "apple",
          explanation: "An apple is a fruit, not a feeling!",
        },
        {
          id: "r3",
          category: "things you can see",
          items: [
            { id: "rainbow", label: "Rainbow", emoji: "🌈" },
            { id: "sun", label: "Sun", emoji: "☀️" },
            { id: "music", label: "Music", emoji: "🎵" },
            { id: "flower", label: "Flower", emoji: "🌸" },
          ],
          oddId: "music",
          explanation: "You hear music with your ears — you can't see it!",
        },
        {
          id: "r4",
          category: "things on your face",
          items: [
            { id: "eyes", label: "Eyes", emoji: "👀" },
            { id: "mouth", label: "Mouth", emoji: "👄" },
            { id: "nose", label: "Nose", emoji: "👃" },
            { id: "knee", label: "Knee", emoji: "🦵" },
            { id: "ears", label: "Ears", emoji: "👂" },
          ],
          oddId: "knee",
          explanation: "Your knee is on your leg, not your face!",
        },
      ],
    },
  },
  {
    id: "aboutme-true-false-body",
    zoneId: "about-me",
    type: "true_false",
    title: "Body Facts: True or False?",
    description: "Test what you know about your body!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Read each fun fact and decide — is it true or false?",
      questions: [
        { id: "tf1", statement: "You have 5 fingers on each hand", emoji: "🖐️", isTrue: true, explanation: "Yes! Five fingers on each hand makes ten total." },
        { id: "tf2", statement: "Your ears help you taste food", emoji: "👂", isTrue: false, explanation: "No! Your tongue helps you taste, not your ears!" },
        { id: "tf3", statement: "Your nose helps you smell flowers", emoji: "👃", isTrue: true, explanation: "That's right! Your nose is your smelling superpower!" },
        { id: "tf4", statement: "You have 3 eyes", emoji: "👀", isTrue: false, explanation: "Nope! Humans have 2 eyes." },
        { id: "tf5", statement: "Your heart pumps blood through your body", emoji: "❤️", isTrue: true, explanation: "Yes! Your heart beats all day and night to keep you alive!" },
      ],
    },
  },
  {
    id: "aboutme-word-body",
    zoneId: "about-me",
    type: "word_picture_link",
    title: "Body Parts Match",
    description: "Connect each word to the right body part!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "word_picture_link",
      instruction: "Tap a word then tap the matching picture!",
      pairs: [
        { id: "eye", word: "Eye", emoji: "👁️" },
        { id: "ear", word: "Ear", emoji: "👂" },
        { id: "nose", word: "Nose", emoji: "👃" },
        { id: "hand", word: "Hand", emoji: "🤲" },
      ],
    },
  },
];
