import type { GameConfig } from "../../types";

// ─────────────────────────────────────────────────────────────────────────────
// 🎮 ADVENTURE GAMES — Animated, character-driven, joystick-style gameplay
// All games use free/open emoji assets — no copyright concerns.
// ─────────────────────────────────────────────────────────────────────────────

export const adventureGamesForAnimals: GameConfig[] = [
  {
    id: "animals-bubble-pop",
    zoneId: "animals",
    type: "bubble_pop",
    title: "Animal Bubble Pop! 🫧",
    description: "Pop only the animal bubbles — don't pop the food ones!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "bubble_pop",
      instruction: "Tap only the ANIMAL bubbles to pop them! Avoid food bubbles.",
      question: "🐾 POP THE ANIMALS!",
      character: "🦊",
      targetHint: "Animals: dog, cat, bird, rabbit, fish...",
      bubbles: [
        { id: "b-dog",    label: "Dog",    emoji: "🐶", isTarget: true,  color: "#fbbf24" },
        { id: "b-cat",    label: "Cat",    emoji: "🐱", isTarget: true,  color: "#f472b6" },
        { id: "b-bird",   label: "Bird",   emoji: "🐦", isTarget: true,  color: "#60a5fa" },
        { id: "b-rabbit", label: "Rabbit", emoji: "🐰", isTarget: true,  color: "#a78bfa" },
        { id: "b-fish",   label: "Fish",   emoji: "🐟", isTarget: true,  color: "#34d399" },
        { id: "b-bear",   label: "Bear",   emoji: "🐻", isTarget: true,  color: "#fb923c" },
        { id: "b-pizza",  label: "Pizza",  emoji: "🍕", isTarget: false, color: "#e5e7eb" },
        { id: "b-apple",  label: "Apple",  emoji: "🍎", isTarget: false, color: "#e5e7eb" },
        { id: "b-cake",   label: "Cake",   emoji: "🎂", isTarget: false, color: "#e5e7eb" },
        { id: "b-star",   label: "Star",   emoji: "⭐", isTarget: false, color: "#e5e7eb" },
        { id: "b-ball",   label: "Ball",   emoji: "⚽", isTarget: false, color: "#e5e7eb" },
      ],
    },
  },
  {
    id: "animals-star-catcher",
    zoneId: "animals",
    type: "star_catcher",
    title: "Wild Animal Catcher! ⭐",
    description: "Catch wild animals, let pets pass. Move with the arrow buttons!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "star_catcher",
      instruction: "Move LEFT ◀ and RIGHT ▶ to catch the wild animals only!",
      question: "🦁 Catch WILD animals!",
      character: "🦊",
      targetCategory: "wild animals",
      lives: 3,
      items: [
        { id: "lion",    label: "Lion",    emoji: "🦁", isTarget: true },
        { id: "tiger",   label: "Tiger",   emoji: "🐯", isTarget: true },
        { id: "elephant",label: "Elephant",emoji: "🐘", isTarget: true },
        { id: "giraffe", label: "Giraffe", emoji: "🦒", isTarget: true },
        { id: "zebra",   label: "Zebra",   emoji: "🦓", isTarget: true },
        { id: "dog",     label: "Dog",     emoji: "🐶", isTarget: false },
        { id: "cat",     label: "Cat",     emoji: "🐱", isTarget: false },
        { id: "cow",     label: "Cow",     emoji: "🐄", isTarget: false },
        { id: "chicken", label: "Chicken", emoji: "🐔", isTarget: false },
      ],
    },
  },
];

export const adventureGamesForFood: GameConfig[] = [
  {
    id: "food-bubble-pop",
    zoneId: "food",
    type: "bubble_pop",
    title: "Healthy Food Pop! 🫧",
    description: "Pop only the healthy food bubbles — avoid junk food!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "bubble_pop",
      instruction: "Pop only HEALTHY food bubbles! Junk food will steal your stars.",
      question: "🥦 POP HEALTHY FOODS!",
      character: "👨‍🍳",
      targetHint: "Fruits, vegetables, grains...",
      bubbles: [
        { id: "f-apple",  label: "Apple",  emoji: "🍎", isTarget: true,  color: "#ef4444" },
        { id: "f-carrot", label: "Carrot", emoji: "🥕", isTarget: true,  color: "#f97316" },
        { id: "f-broc",   label: "Broccoli",emoji: "🥦", isTarget: true, color: "#22c55e" },
        { id: "f-banana", label: "Banana", emoji: "🍌", isTarget: true,  color: "#fbbf24" },
        { id: "f-grapes", label: "Grapes", emoji: "🍇", isTarget: true,  color: "#8b5cf6" },
        { id: "f-milk",   label: "Milk",   emoji: "🥛", isTarget: true,  color: "#60a5fa" },
        { id: "f-pizza",  label: "Pizza",  emoji: "🍕", isTarget: false, color: "#e5e7eb" },
        { id: "f-candy",  label: "Candy",  emoji: "🍬", isTarget: false, color: "#e5e7eb" },
        { id: "f-chips",  label: "Chips",  emoji: "🍟", isTarget: false, color: "#e5e7eb" },
        { id: "f-soda",   label: "Soda",   emoji: "🥤", isTarget: false, color: "#e5e7eb" },
        { id: "f-cake",   label: "Cake",   emoji: "🎂", isTarget: false, color: "#e5e7eb" },
      ],
    },
  },
  {
    id: "food-star-catcher",
    zoneId: "food",
    type: "star_catcher",
    title: "Fruit Catcher! ⭐",
    description: "Catch only fruits falling from the sky!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "star_catcher",
      instruction: "Catch falling FRUITS with your basket! Let vegetables pass.",
      question: "🍎 Catch the FRUITS!",
      character: "🧒",
      targetCategory: "fruits",
      lives: 3,
      items: [
        { id: "apple",      label: "Apple",      emoji: "🍎", isTarget: true },
        { id: "banana",     label: "Banana",     emoji: "🍌", isTarget: true },
        { id: "grapes",     label: "Grapes",     emoji: "🍇", isTarget: true },
        { id: "watermelon", label: "Watermelon", emoji: "🍉", isTarget: true },
        { id: "strawberry", label: "Strawberry", emoji: "🍓", isTarget: true },
        { id: "carrot",     label: "Carrot",     emoji: "🥕", isTarget: false },
        { id: "broccoli",   label: "Broccoli",   emoji: "🥦", isTarget: false },
        { id: "onion",      label: "Onion",      emoji: "🧅", isTarget: false },
        { id: "corn",       label: "Corn",       emoji: "🌽", isTarget: false },
      ],
    },
  },
];

export const adventureGamesForPlants: GameConfig[] = [
  {
    id: "plants-bubble-pop",
    zoneId: "plants",
    type: "bubble_pop",
    title: "Plant Parts Pop! 🫧",
    description: "Pop bubbles with plant parts — ignore the non-plant items!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "bubble_pop",
      instruction: "Pop only PLANT PART bubbles! Ignore animals and food.",
      question: "🌱 POP PLANT PARTS!",
      character: "🌻",
      targetHint: "Roots, stem, leaf, flower, fruit, seed...",
      bubbles: [
        { id: "p-root",   label: "Root",   emoji: "🌿", isTarget: true,  color: "#854d0e" },
        { id: "p-stem",   label: "Stem",   emoji: "🪴", isTarget: true,  color: "#16a34a" },
        { id: "p-leaf",   label: "Leaf",   emoji: "🍃", isTarget: true,  color: "#22c55e" },
        { id: "p-flower", label: "Flower", emoji: "🌸", isTarget: true,  color: "#f472b6" },
        { id: "p-fruit",  label: "Fruit",  emoji: "🍑", isTarget: true,  color: "#fb923c" },
        { id: "p-seed",   label: "Seed",   emoji: "🌰", isTarget: true,  color: "#92400e" },
        { id: "p-dog",    label: "Dog",    emoji: "🐶", isTarget: false, color: "#e5e7eb" },
        { id: "p-car",    label: "Car",    emoji: "🚗", isTarget: false, color: "#e5e7eb" },
        { id: "p-moon",   label: "Moon",   emoji: "🌙", isTarget: false, color: "#e5e7eb" },
        { id: "p-shoe",   label: "Shoe",   emoji: "👟", isTarget: false, color: "#e5e7eb" },
      ],
    },
  },
];

export const adventureGamesForAboutMe: GameConfig[] = [
  {
    id: "aboutme-star-catcher",
    zoneId: "about-me",
    type: "star_catcher",
    title: "Body Parts Catcher! ⭐",
    description: "Catch items that are body parts — let the other things fall!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "star_catcher",
      instruction: "Use ◀ ▶ buttons to catch BODY PARTS! Let other things fall through.",
      question: "🖐 Catch BODY PARTS!",
      character: "🧒",
      targetCategory: "body parts",
      lives: 4,
      items: [
        { id: "eyes",  label: "Eyes",  emoji: "👀", isTarget: true },
        { id: "nose",  label: "Nose",  emoji: "👃", isTarget: true },
        { id: "ear",   label: "Ear",   emoji: "👂", isTarget: true },
        { id: "hand",  label: "Hand",  emoji: "🖐", isTarget: true },
        { id: "foot",  label: "Foot",  emoji: "🦶", isTarget: true },
        { id: "mouth", label: "Mouth", emoji: "👄", isTarget: true },
        { id: "ball",  label: "Ball",  emoji: "⚽", isTarget: false },
        { id: "sun",   label: "Sun",   emoji: "☀️", isTarget: false },
        { id: "tree",  label: "Tree",  emoji: "🌳", isTarget: false },
        { id: "house", label: "House", emoji: "🏠", isTarget: false },
      ],
    },
  },
  {
    id: "aboutme-feelings-bubble",
    zoneId: "about-me",
    type: "bubble_pop",
    title: "Happy Feelings Pop! 🫧",
    description: "Pop the HAPPY feeling bubbles! Avoid the sad ones.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "bubble_pop",
      instruction: "Pop bubbles showing HAPPY feelings! Leave the sad ones.",
      question: "😊 POP HAPPY FEELINGS!",
      character: "😊",
      targetHint: "Happy, excited, loved, proud, silly...",
      bubbles: [
        { id: "happy",   label: "Happy",   emoji: "😊", isTarget: true,  color: "#fbbf24" },
        { id: "excited", label: "Excited", emoji: "🤩", isTarget: true,  color: "#f472b6" },
        { id: "proud",   label: "Proud",   emoji: "😎", isTarget: true,  color: "#60a5fa" },
        { id: "loved",   label: "Loved",   emoji: "🥰", isTarget: true,  color: "#f472b6" },
        { id: "silly",   label: "Silly",   emoji: "🤪", isTarget: true,  color: "#a78bfa" },
        { id: "sad",     label: "Sad",     emoji: "😢", isTarget: false, color: "#e5e7eb" },
        { id: "angry",   label: "Angry",   emoji: "😠", isTarget: false, color: "#e5e7eb" },
        { id: "scared",  label: "Scared",  emoji: "😨", isTarget: false, color: "#e5e7eb" },
        { id: "tired",   label: "Tired",   emoji: "😴", isTarget: false, color: "#e5e7eb" },
      ],
    },
  },
];

export const adventureGamesForTransport: GameConfig[] = [
  {
    id: "transport-star-catcher",
    zoneId: "transport",
    type: "star_catcher",
    title: "Air Transport Catcher! ⭐",
    description: "Catch only vehicles that travel through AIR!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "star_catcher",
      instruction: "Catch things that FLY in the air! Let land/water transport pass.",
      question: "✈️ Catch AIR transport!",
      character: "👨‍✈️",
      targetCategory: "air transport",
      lives: 3,
      items: [
        { id: "plane",      label: "Plane",      emoji: "✈️", isTarget: true },
        { id: "helicopter", label: "Helicopter", emoji: "🚁", isTarget: true },
        { id: "rocket",     label: "Rocket",     emoji: "🚀", isTarget: true },
        { id: "balloon",    label: "Balloon",    emoji: "🎈", isTarget: true },
        { id: "car",        label: "Car",        emoji: "🚗", isTarget: false },
        { id: "bus",        label: "Bus",        emoji: "🚌", isTarget: false },
        { id: "train",      label: "Train",      emoji: "🚂", isTarget: false },
        { id: "boat",       label: "Boat",       emoji: "⛵", isTarget: false },
        { id: "bicycle",    label: "Bicycle",    emoji: "🚲", isTarget: false },
      ],
    },
  },
];

export const adventureGamesForHealth: GameConfig[] = [
  {
    id: "health-bubble-pop",
    zoneId: "health-safety",
    type: "bubble_pop",
    title: "Good Habits Pop! 🫧",
    description: "Pop bubbles showing GOOD health habits!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "bubble_pop",
      instruction: "Pop only GOOD HABIT bubbles! Leave the bad habits alone.",
      question: "🪥 POP GOOD HABITS!",
      character: "🧒",
      targetHint: "Washing hands, brushing teeth, exercising...",
      bubbles: [
        { id: "wash",     label: "Wash Hands",    emoji: "🙌", isTarget: true,  color: "#60a5fa" },
        { id: "brush",    label: "Brush Teeth",   emoji: "🪥", isTarget: true,  color: "#a78bfa" },
        { id: "exercise", label: "Exercise",      emoji: "🏃", isTarget: true,  color: "#22c55e" },
        { id: "sleep",    label: "Sleep Early",   emoji: "😴", isTarget: true,  color: "#818cf8" },
        { id: "eat",      label: "Eat Veggies",   emoji: "🥦", isTarget: true,  color: "#34d399" },
        { id: "drink",    label: "Drink Water",   emoji: "💧", isTarget: true,  color: "#38bdf8" },
        { id: "junk",     label: "Eat Junk",      emoji: "🍔", isTarget: false, color: "#e5e7eb" },
        { id: "nosleep",  label: "Stay Up Late",  emoji: "📱", isTarget: false, color: "#e5e7eb" },
        { id: "dirty",    label: "Dirty Hands",   emoji: "🤢", isTarget: false, color: "#e5e7eb" },
        { id: "litter",   label: "Littering",     emoji: "🗑️", isTarget: false, color: "#e5e7eb" },
      ],
    },
  },
];

// Aggregated exports per zone
export const adventureGamesByZone: Record<string, GameConfig[]> = {
  animals: adventureGamesForAnimals,
  food: adventureGamesForFood,
  plants: adventureGamesForPlants,
  "about-me": adventureGamesForAboutMe,
  transport: adventureGamesForTransport,
  "health-safety": adventureGamesForHealth,
};
