import type { GameConfig } from "../../types";

export const animalsGames: GameConfig[] = [
  {
    id: "animals-book-ch3-read",
    zoneId: "animals",
    type: "interactive_story",
    title: "Animals that Help Us",
    description: "Chapter 3 from your book — read what domestic animals do for us.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "interactive_story",
      instruction:
        "Listen to the lines from Chapter 3: Animals that Help Us. Tap Next on each page.",
      pages: [
        {
          id: "p1",
          text:
            "Domestic animals are tamed by people. They help in doing various tasks. People provide food, water and shelter to such animals. Let us learn more about them.",
          emoji: "🏠",
        },
        {
          id: "p2",
          text: "We all give milk. — Camel, Buffalo, Goat, Cow.",
          emoji: "🥛",
        },
        {
          id: "p3",
          text: "We all give eggs. — Duck, Hen, Goose.",
          emoji: "🥚",
        },
        {
          id: "p4",
          text: "We give silk. — Silkworms.",
          emoji: "🐛",
        },
        {
          id: "p5",
          text:
            "We provide food to the soil and help the plants to grow. — Earthworms.",
          emoji: "🪱",
        },
        {
          id: "p6",
          text: "Some people eat our flesh. — Fish, Hen, Goat.",
          emoji: "🐟",
        },
        {
          id: "p7",
          text: "We give honey. — Honey bee.",
          emoji: "🍯",
        },
        {
          id: "p8",
          text: "We give wool. — Sheep.",
          emoji: "🐑",
        },
        {
          id: "p9",
          text: "We carry load. — Horse, Camel, Donkey, Bull, Elephant.",
          emoji: "🐴",
        },
        {
          id: "p10",
          text: "We help in agriculture. — Bull (with the plough).",
          emoji: "🌾",
        },
      ],
    },
  },
  {
    id: "animals-pixi-helpful-lab",
    zoneId: "animals",
    type: "pixi_lab",
    title: "Helpful animals lab",
    description: "WebGL drag lab — match animals to milk, eggs, wool, or honey (Chapter 3).",
    difficulty: 2,
    maxStars: 3,
    bookPageSrc: "/syllabus-photos/20260328_104740.jpg",
    data: {
      type: "pixi_lab",
      mode: "animal_product",
      instruction:
        "Drag each animal into the right box. Build a streak for bonus points — your book groups them the same way!",
      bins: [
        { id: "milk", label: "Milk", emoji: "🥛" },
        { id: "eggs", label: "Eggs", emoji: "🥚" },
        { id: "wool", label: "Wool", emoji: "🧶" },
        { id: "honey", label: "Honey", emoji: "🍯" },
      ],
      creatures: [
        { id: "cow", emoji: "🐄", label: "Cow", correctBinId: "milk" },
        { id: "goat", emoji: "🐐", label: "Goat", correctBinId: "milk" },
        { id: "buffalo", emoji: "🐃", label: "Buffalo", correctBinId: "milk" },
        { id: "camel", emoji: "🐪", label: "Camel", correctBinId: "milk" },
        { id: "hen", emoji: "🐔", label: "Hen", correctBinId: "eggs" },
        { id: "duck", emoji: "🦆", label: "Duck", correctBinId: "eggs" },
        { id: "goose", emoji: "🪿", label: "Goose", correctBinId: "eggs" },
        { id: "sheep", emoji: "🐑", label: "Sheep", correctBinId: "wool" },
        { id: "bee", emoji: "🐝", label: "Honey bee", correctBinId: "honey" },
      ],
    },
  },
  {
    id: "animals-pixi-word-smart",
    zoneId: "animals",
    type: "pixi_lab",
    title: "Word Smart — unscramble",
    description: "WebGL drag letters — like MI Word Smart on Animals that Help Us.",
    difficulty: 2,
    maxStars: 3,
    bookPageSrc: "/syllabus-photos/20260328_104740.jpg",
    data: {
      type: "pixi_lab",
      mode: "word_unscramble",
      instruction:
        "Drag each letter into the boxes to spell the animal’s name. Wrong spellings bounce back — try again!",
      rounds: [
        { id: "w1", emoji: "🐔", word: "HEN" },
        { id: "w2", emoji: "🐄", word: "COW" },
        { id: "w3", emoji: "🐕", word: "DOG" },
        { id: "w4", emoji: "🫏", word: "DONKEY" },
        { id: "w5", emoji: "🐴", word: "HORSE" },
        { id: "w6", emoji: "🐑", word: "SHEEP" },
      ],
    },
  },
  {
    id: "animals-book-ch3-true-false",
    zoneId: "animals",
    type: "true_false",
    title: "Chapter 3 — True or False",
    description: "Check ideas from Animals that Help Us.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "These ideas come from your textbook. Are they true or false?",
      questions: [
        {
          id: "tf1",
          statement: "Domestic animals are tamed by people.",
          emoji: "🐄",
          isTrue: true,
          explanation: "Your book says domestic animals are tamed by people.",
        },
        {
          id: "tf2",
          statement: "People provide food, water and shelter to domestic animals.",
          emoji: "🏡",
          isTrue: true,
          explanation: "That is what Chapter 3 explains.",
        },
        {
          id: "tf3",
          statement: "Sheep give us honey.",
          emoji: "🐑",
          isTrue: false,
          explanation: "Sheep give wool. Honey comes from the honey bee.",
        },
        {
          id: "tf4",
          statement: "Earthworms help plants grow.",
          emoji: "🪱",
          isTrue: true,
          explanation: "They provide food to the soil and help plants grow.",
        },
        {
          id: "tf5",
          statement: "Silkworms give us wool.",
          emoji: "🐛",
          isTrue: false,
          explanation: "Silkworms give silk. Sheep give wool.",
        },
      ],
    },
  },
  {
    id: "animals-book-how-they-help",
    zoneId: "animals",
    type: "drag_sort",
    title: "How animals help us",
    description: "Sort animals into the same groups as Chapter 3.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Pick an animal, then tap the box that matches what your book says they give or do.",
      categories: [
        { id: "milk", label: "We all give milk", emoji: "🥛" },
        { id: "eggs", label: "We all give eggs", emoji: "🥚" },
        { id: "silk", label: "We give silk", emoji: "🐛" },
        { id: "soil", label: "Soil & plant helpers", emoji: "🪱" },
        { id: "honey", label: "We give honey", emoji: "🍯" },
        { id: "wool", label: "We give wool", emoji: "🐑" },
      ],
      items: [
        { id: "camel", label: "Camel", emoji: "🐪", category: "milk" },
        { id: "buffalo", label: "Buffalo", emoji: "🐃", category: "milk" },
        { id: "goat", label: "Goat", emoji: "🐐", category: "milk" },
        { id: "cow", label: "Cow", emoji: "🐄", category: "milk" },
        { id: "duck", label: "Duck", emoji: "🦆", category: "eggs" },
        { id: "hen", label: "Hen", emoji: "🐔", category: "eggs" },
        { id: "goose", label: "Goose", emoji: "🪿", category: "eggs" },
        { id: "silkworm", label: "Silkworms", emoji: "🐛", category: "silk" },
        { id: "earthworm", label: "Earthworms", emoji: "🪱", category: "soil" },
        { id: "bee", label: "Honey bee", emoji: "🐝", category: "honey" },
        { id: "sheep", label: "Sheep", emoji: "🐑", category: "wool" },
      ],
    },
  },
  {
    id: "animals-book-load-and-farm",
    zoneId: "animals",
    type: "drag_sort",
    title: "Load and farming",
    description: "Match animals that carry load or help in agriculture.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Your book says some animals carry load and some help in agriculture. Sort each one.",
      categories: [
        { id: "load", label: "We carry load", emoji: "📦" },
        { id: "farm", label: "We help in agriculture", emoji: "🌾" },
      ],
      items: [
        { id: "horse", label: "Horse", emoji: "🐴", category: "load" },
        { id: "camel2", label: "Camel", emoji: "🐪", category: "load" },
        { id: "donkey", label: "Donkey", emoji: "🫏", category: "load" },
        { id: "elephant", label: "Elephant", emoji: "🐘", category: "load" },
        { id: "bull_load", label: "Bull", emoji: "🐂", category: "load" },
        { id: "bull_plough", label: "Bulls ploughing", emoji: "🐂", category: "farm" },
      ],
    },
  },
  {
    id: "animals-book-word-smart",
    zoneId: "animals",
    type: "word_picture_link",
    title: "WORD SMART — Unscramble",
    description: "Same activity as the book: unscramble useful animal names.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "word_picture_link",
      instruction:
        "WORD SMART — Unscramble the names of these useful animals (from your textbook).",
      matchHint: "Tap a scrambled name, then tap the matching animal picture!",
      pairs: [
        { id: "hen", word: "Hen", wordDisplay: "hne", emoji: "🐔" },
        { id: "cow", word: "Cow", wordDisplay: "ocw", emoji: "🐄" },
        { id: "dog", word: "Dog", wordDisplay: "ogd", emoji: "🐕" },
        { id: "donkey", word: "Donkey", wordDisplay: "kdoeyn", emoji: "🫏" },
        { id: "horse", word: "Horse", wordDisplay: "ohser", emoji: "🐴" },
        { id: "sheep", word: "Sheep", wordDisplay: "hesep", emoji: "🐑" },
      ],
    },
  },
  {
    id: "animals-ch4-wild-facts",
    zoneId: "animals",
    type: "true_false",
    title: "Wild animals (Chapter 4)",
    description: "Ideas from New Learning Science — Eco Smart.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction:
        "Wild animals live in forests and find their own food, water, shelter and space. Are these lines true or false?",
      questions: [
        {
          id: "w1",
          statement:
            "Animals that live in natural conditions like forests are called wild animals.",
          emoji: "🌳",
          isTrue: true,
          explanation: "Your book says wild animals live in natural places, unlike domestic animals.",
        },
        {
          id: "w2",
          statement: "We should kill wild animals for fun or for their skin.",
          emoji: "🐅",
          isTrue: false,
          explanation: "The book says we must protect animals and not kill them for sport or skin.",
        },
        {
          id: "w3",
          statement: "Vultures eat the flesh of dead animals.",
          emoji: "🦅",
          isTrue: true,
          explanation: "Scavengers like vultures eat dead animals — your book calls them scavengers.",
        },
        {
          id: "w4",
          statement: "A lion lives in water.",
          emoji: "🦁",
          isTrue: false,
          explanation: "Lions live on land — often in forests — not in water.",
        },
      ],
    },
  },
  {
    id: "animals-food-habits-sort",
    zoneId: "animals",
    type: "drag_sort",
    title: "What do they eat?",
    description: "Herbivores, carnivores, scavengers and omnivores — from your book.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Sort each animal into how it eats: plants only, other animals, dead animals, or both plants and animals.",
      categories: [
        { id: "herb", label: "Eat plants", emoji: "🌿" },
        { id: "carn", label: "Eat other animals", emoji: "🥩" },
        { id: "scav", label: "Eat dead animals", emoji: "🦴" },
        { id: "omni", label: "Eat plants & animals", emoji: "🐻" },
      ],
      items: [
        { id: "deer", label: "Deer", emoji: "🦌", category: "herb" },
        { id: "giraffe", label: "Giraffe", emoji: "🦒", category: "herb" },
        { id: "elephant", label: "Elephant", emoji: "🐘", category: "herb" },
        { id: "lion", label: "Lion", emoji: "🦁", category: "carn" },
        { id: "tiger", label: "Tiger", emoji: "🐯", category: "carn" },
        { id: "croc", label: "Crocodile", emoji: "🐊", category: "carn" },
        { id: "vulture", label: "Vulture", emoji: "🦅", category: "scav" },
        { id: "hyena", label: "Hyena", emoji: "🐺", category: "scav" },
        { id: "bear", label: "Bear", emoji: "🐻", category: "omni" },
        { id: "crow", label: "Crow", emoji: "🐦‍⬛", category: "omni" },
      ],
    },
  },
  {
    id: "animals-wild-pet-sort",
    zoneId: "animals",
    type: "drag_sort",
    title: "Wild or Pet?",
    description: "Sort animals into wild animals and pets — extra practice.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Does this animal live in the wild or at home as a pet?",
      categories: [
        { id: "wild", label: "Wild Animals", emoji: "🦁" },
        { id: "pet", label: "Pets", emoji: "🏠" },
      ],
      items: [
        { id: "lion", label: "Lion", emoji: "🦁", category: "wild" },
        { id: "dog", label: "Dog", emoji: "🐕", category: "pet" },
        { id: "elephant", label: "Elephant", emoji: "🐘", category: "wild" },
        { id: "cat", label: "Cat", emoji: "🐱", category: "pet" },
        { id: "tiger", label: "Tiger", emoji: "🐯", category: "wild" },
        { id: "rabbit", label: "Rabbit", emoji: "🐰", category: "pet" },
        { id: "bear", label: "Bear", emoji: "🐻", category: "wild" },
        { id: "goldfish", label: "Goldfish", emoji: "🐠", category: "pet" },
      ],
    },
  },
  {
    id: "animals-sounds-quiz",
    zoneId: "animals",
    type: "picture_quiz",
    title: "Animal Sounds",
    description: "Which animal makes this sound?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Listen to the clue and pick the right animal!",
      questions: [
        {
          id: "q1",
          question: "Which animal says 'Moo'?",
          options: [
            { id: "cow", label: "Cow", emoji: "🐄" },
            { id: "dog", label: "Dog", emoji: "🐕" },
            { id: "cat", label: "Cat", emoji: "🐱" },
            { id: "duck", label: "Duck", emoji: "🦆" },
          ],
          correctId: "cow",
          explanation: "Cows say 'Moo'! They give milk like in Chapter 3.",
        },
        {
          id: "q2",
          question: "Which animal says 'Quack'?",
          options: [
            { id: "horse", label: "Horse", emoji: "🐴" },
            { id: "sheep", label: "Sheep", emoji: "🐑" },
            { id: "duck", label: "Duck", emoji: "🦆" },
            { id: "pig", label: "Pig", emoji: "🐷" },
          ],
          correctId: "duck",
          explanation: "Ducks say 'Quack'! Your book lists duck under egg layers.",
        },
        {
          id: "q3",
          question: "Which animal roars loudly?",
          options: [
            { id: "rabbit", label: "Rabbit", emoji: "🐰" },
            { id: "lion", label: "Lion", emoji: "🦁" },
            { id: "fish", label: "Fish", emoji: "🐟" },
            { id: "butterfly", label: "Butterfly", emoji: "🦋" },
          ],
          correctId: "lion",
          explanation: "Lions roar loudly — they are wild animals.",
        },
        {
          id: "q4",
          question: "Which animal says 'Baa'?",
          options: [
            { id: "sheep", label: "Sheep", emoji: "🐑" },
            { id: "frog", label: "Frog", emoji: "🐸" },
            { id: "parrot", label: "Parrot", emoji: "🦜" },
            { id: "snake", label: "Snake", emoji: "🐍" },
          ],
          correctId: "sheep",
          explanation: "Sheep say 'Baa'! Chapter 3 says sheep give wool.",
        },
      ],
    },
  },
  {
    id: "animals-baby-match",
    zoneId: "animals",
    type: "memory_match",
    title: "Baby Animals",
    description: "Match the animal with its baby name!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Find the matching pairs — each animal has a baby!",
      pairs: [
        { id: "dog", front: "Dog → Puppy", emoji: "🐶" },
        { id: "cat", front: "Cat → Kitten", emoji: "🐱" },
        { id: "hen", front: "Hen → Chick", emoji: "🐣" },
        { id: "cow", front: "Cow → Calf", emoji: "🐄" },
        { id: "horse", front: "Horse → Foal", emoji: "🐴" },
        { id: "frog", front: "Frog → Tadpole", emoji: "🐸" },
      ],
    },
  },
  {
    id: "animals-life-sequence",
    zoneId: "animals",
    type: "sequence_builder",
    title: "Butterfly Life Cycle",
    description: "Arrange the stages of a butterfly's life!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "Put the butterfly's life stages in order!",
      steps: [
        { id: "egg", label: "Egg", emoji: "🥚", order: 1 },
        { id: "caterpillar", label: "Caterpillar", emoji: "🐛", order: 2 },
        { id: "chrysalis", label: "Chrysalis", emoji: "🫧", order: 3 },
        { id: "butterfly", label: "Butterfly!", emoji: "🦋", order: 4 },
      ],
    },
  },
  {
    id: "animals-word-picture",
    zoneId: "animals",
    type: "word_picture_link",
    title: "Animal Names",
    description: "Match each word to its picture — quick review.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "word_picture_link",
      instruction: "Tap a word, then tap the matching picture!",
      pairs: [
        { id: "dog", word: "Dog", emoji: "🐕" },
        { id: "cat", word: "Cat", emoji: "🐱" },
        { id: "bird", word: "Bird", emoji: "🐦" },
        { id: "fish", word: "Fish", emoji: "🐟" },
        { id: "rabbit", word: "Rabbit", emoji: "🐰" },
      ],
    },
  },
  {
    id: "animals-story-lost-puppy",
    zoneId: "animals",
    type: "interactive_story",
    title: "The Lost Puppy",
    description: "Help the lost puppy find its way home!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "interactive_story",
      instruction: "Read the story and make choices to help the puppy!",
      pages: [
        {
          id: "p1",
          text: "A little puppy is lost in the park. It looks scared and hungry. What should you do?",
          emoji: "🐶",
          choices: [
            { id: "c1a", label: "Give it some water and food", nextPageId: "p2", correct: true },
            { id: "c1b", label: "Run away from it", nextPageId: "p2wrong", correct: false },
          ],
        },
        {
          id: "p2wrong",
          text: "Oh no, the puppy is still alone and scared. Let's go back and help it!",
          emoji: "😟",
          choices: [
            { id: "c2a", label: "Go back and help the puppy", nextPageId: "p2", correct: true },
            { id: "c2b", label: "Keep walking away", nextPageId: "p2", correct: false },
          ],
        },
        {
          id: "p2",
          text: "The puppy wags its tail happily! It has a collar with a phone number. What should you do?",
          emoji: "🐕",
          choices: [
            { id: "c3a", label: "Ask a parent to call the number", nextPageId: "p3", correct: true },
            { id: "c3b", label: "Keep the puppy for yourself", nextPageId: "p3", correct: false },
          ],
        },
        {
          id: "p3",
          text: "The owner comes running and hugs the puppy! 'Thank you for taking care of my dog!' they say. You're a hero!",
          emoji: "🎉",
        },
      ],
    },
  },
];
