import type { GameConfig } from "../../types";

export const animalsGames: GameConfig[] = [
  {
    id: "animals-wild-pet-sort",
    zoneId: "animals",
    type: "drag_sort",
    title: "Wild or Pet?",
    description: "Sort the animals into wild animals and pets!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Does this animal live in the wild or at home as a pet?",
      categories: [
        { id: "wild", label: "Wild Animals", emoji: "🦁" },
        { id: "pet", label: "Pets", emoji: "🏠" },
      ],
      items: [
        { id: "lion", label: "Lion", emoji: "🦁", category: "wild" },
        { id: "dog", label: "Dog", emoji: "🐕", category: "pet" },
        { id: "elephant", label: "Elephant", emoji: "🐘", category: "wild" },
        { id: "cat", label: "Cat", emoji: "🐱", category: "pet" },
        { id: "tiger", label: "Tiger", emoji: "🐯", category: "wild" },
        { id: "rabbit", label: "Rabbit", emoji: "🐰", category: "pet" },
        { id: "bear", label: "Bear", emoji: "🐻", category: "wild" },
        { id: "goldfish", label: "Goldfish", emoji: "🐠", category: "pet" },
      ],
    },
  },
  {
    id: "animals-sounds-quiz",
    zoneId: "animals",
    type: "picture_quiz",
    title: "Animal Sounds",
    description: "Which animal makes this sound?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Listen to the sound and pick the right animal!",
      questions: [
        {
          id: "q1",
          question: "Which animal says 'Moo'?",
          options: [
            { id: "cow", label: "Cow", emoji: "🐄" },
            { id: "dog", label: "Dog", emoji: "🐕" },
            { id: "cat", label: "Cat", emoji: "🐱" },
            { id: "duck", label: "Duck", emoji: "🦆" },
          ],
          correctId: "cow",
          explanation: "Cows say 'Moo'! They live on farms and give us milk.",
        },
        {
          id: "q2",
          question: "Which animal says 'Quack'?",
          options: [
            { id: "horse", label: "Horse", emoji: "🐴" },
            { id: "sheep", label: "Sheep", emoji: "🐑" },
            { id: "duck", label: "Duck", emoji: "🦆" },
            { id: "pig", label: "Pig", emoji: "🐷" },
          ],
          correctId: "duck",
          explanation: "Ducks say 'Quack'! They love swimming in ponds.",
        },
        {
          id: "q3",
          question: "Which animal roars loudly?",
          options: [
            { id: "rabbit", label: "Rabbit", emoji: "🐰" },
            { id: "lion", label: "Lion", emoji: "🦁" },
            { id: "fish", label: "Fish", emoji: "🐟" },
            { id: "butterfly", label: "Butterfly", emoji: "🦋" },
          ],
          correctId: "lion",
          explanation: "Lions are the king of the jungle — their roar can be heard from far away!",
        },
        {
          id: "q4",
          question: "Which animal says 'Baa'?",
          options: [
            { id: "sheep", label: "Sheep", emoji: "🐑" },
            { id: "frog", label: "Frog", emoji: "🐸" },
            { id: "parrot", label: "Parrot", emoji: "🦜" },
            { id: "snake", label: "Snake", emoji: "🐍" },
          ],
          correctId: "sheep",
          explanation: "Sheep say 'Baa'! Their woolly coats keep them warm.",
        },
      ],
    },
  },
  {
    id: "animals-baby-match",
    zoneId: "animals",
    type: "memory_match",
    title: "Baby Animals",
    description: "Match the animal with its baby name!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Find the matching pairs — each animal has a baby!",
      pairs: [
        { id: "dog", front: "Dog → Puppy", emoji: "🐶" },
        { id: "cat", front: "Cat → Kitten", emoji: "🐱" },
        { id: "hen", front: "Hen → Chick", emoji: "🐣" },
        { id: "cow", front: "Cow → Calf", emoji: "🐄" },
        { id: "horse", front: "Horse → Foal", emoji: "🐴" },
        { id: "frog", front: "Frog → Tadpole", emoji: "🐸" },
      ],
    },
  },
  {
    id: "animals-life-sequence",
    zoneId: "animals",
    type: "sequence_builder",
    title: "Butterfly Life Cycle",
    description: "Arrange the stages of a butterfly's life!",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "Put the butterfly's life stages in order!",
      steps: [
        { id: "egg", label: "Egg", emoji: "🥚", order: 1 },
        { id: "caterpillar", label: "Caterpillar", emoji: "🐛", order: 2 },
        { id: "chrysalis", label: "Chrysalis", emoji: "🫧", order: 3 },
        { id: "butterfly", label: "Butterfly!", emoji: "🦋", order: 4 },
      ],
    },
  },
  {
    id: "animals-word-picture",
    zoneId: "animals",
    type: "word_picture_link",
    title: "Animal Names",
    description: "Match each animal name to its picture!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "word_picture_link",
      instruction: "Tap a word, then tap the matching picture!",
      pairs: [
        { id: "dog", word: "Dog", emoji: "🐕" },
        { id: "cat", word: "Cat", emoji: "🐱" },
        { id: "bird", word: "Bird", emoji: "🐦" },
        { id: "fish", word: "Fish", emoji: "🐟" },
        { id: "rabbit", word: "Rabbit", emoji: "🐰" },
      ],
    },
  },
  {
    id: "animals-story-lost-puppy",
    zoneId: "animals",
    type: "interactive_story",
    title: "The Lost Puppy",
    description: "Help the lost puppy find its way home!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "interactive_story",
      instruction: "Read the story and make choices to help the puppy!",
      pages: [
        {
          id: "p1",
          text: "A little puppy is lost in the park. It looks scared and hungry. What should you do?",
          emoji: "🐶",
          choices: [
            { id: "c1a", label: "Give it some water and food", nextPageId: "p2", correct: true },
            { id: "c1b", label: "Run away from it", nextPageId: "p2wrong", correct: false },
          ],
        },
        {
          id: "p2wrong",
          text: "Oh no, the puppy is still alone and scared. Let's go back and help it!",
          emoji: "😟",
          choices: [
            { id: "c2a", label: "Go back and help the puppy", nextPageId: "p2", correct: true },
            { id: "c2b", label: "Keep walking away", nextPageId: "p2", correct: false },
          ],
        },
        {
          id: "p2",
          text: "The puppy wags its tail happily! It has a collar with a phone number. What should you do?",
          emoji: "🐕",
          choices: [
            { id: "c3a", label: "Ask a parent to call the number", nextPageId: "p3", correct: true },
            { id: "c3b", label: "Keep the puppy for yourself", nextPageId: "p3", correct: false },
          ],
        },
        {
          id: "p3",
          text: "The owner comes running and hugs the puppy! 'Thank you for taking care of my dog!' they say. You're a hero!",
          emoji: "🎉",
        },
      ],
    },
  },
];
