import type { GameConfig } from "../../types";

export const communicationGames: GameConfig[] = [
  {
    id: "communication-old-new-sort",
    zoneId: "communication",
    type: "drag_sort",
    title: "Old vs New Communication",
    description: "How people shared messages long ago and today!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Sort old-fashioned ways and newer ways to communicate!",
      categories: [
        { id: "old", label: "Long Ago", emoji: "📜" },
        { id: "new", label: "Today", emoji: "📱" },
      ],
      items: [
        { id: "letter", label: "Handwritten letter", emoji: "✉️", category: "old" },
        { id: "email", label: "Email", emoji: "📧", category: "new" },
        { id: "pigeon", label: "Carrier pigeon", emoji: "🕊️", category: "old" },
        { id: "phone", label: "Mobile phone call", emoji: "📞", category: "new" },
        { id: "telegram", label: "Telegram (old wire message)", emoji: "📠", category: "old" },
        { id: "video", label: "Video chat", emoji: "💻", category: "new" },
        { id: "smoke", label: "Smoke signals (storybook)", emoji: "💨", category: "old" },
        { id: "text", label: "Text message", emoji: "💬", category: "new" },
      ],
    },
  },
  {
    id: "communication-letter-sequence",
    zoneId: "communication",
    type: "sequence_builder",
    title: "Send a Letter",
    description: "Put the steps to send a real letter in order!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "How does a letter travel to grandma's house?",
      steps: [
        { id: "write", label: "Write your message", emoji: "✍️", order: 1 },
        { id: "fold", label: "Fold and put in envelope", emoji: "📨", order: 2 },
        { id: "stamp", label: "Add address & stamp", emoji: "📮", order: 3 },
        { id: "mailbox", label: "Post in mailbox", emoji: "📬", order: 4 },
        { id: "postman", label: "Post office sorts & sends", emoji: "🚚", order: 5 },
        { id: "deliver", label: "Delivered — they read it!", emoji: "😊", order: 6 },
      ],
    },
  },
  {
    id: "communication-quiz",
    zoneId: "communication",
    type: "picture_quiz",
    title: "Communication Quiz",
    description: "How do we share ideas and feelings?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Pick the best way to communicate!",
      questions: [
        {
          id: "q1",
          question: "You want to say hello to a friend far away quickly. What works well?",
          options: [
            { id: "shout", label: "Shout out the window", emoji: "📢" },
            { id: "call", label: "Phone or video call with help", emoji: "📱" },
            { id: "buried", label: "Bury a note in sand", emoji: "🏖️" },
            { id: "ignore", label: "Say nothing forever", emoji: "🙊" },
          ],
          correctId: "call",
          explanation: "Phones and apps let us talk to people anywhere in seconds!",
        },
        {
          id: "q2",
          question: "Which is a kind way to communicate in person?",
          options: [
            { id: "listen", label: "Listen and use polite words", emoji: "🙂" },
            { id: "yell", label: "Yell over everyone", emoji: "😡" },
            { id: "point", label: "Point and laugh meanly", emoji: "👎" },
            { id: "walk-away", label: "Walk away mid-sentence always", emoji: "🚶" },
          ],
          correctId: "listen",
          explanation: "Listening and kind words help friends understand each other!",
        },
        {
          id: "q3",
          question: "Books and stories communicate using…",
          options: [
            { id: "words", label: "Words and pictures", emoji: "📚" },
            { id: "only-beeps", label: "Only loud beeps", emoji: "📢" },
            { id: "smell-only", label: "Only smells", emoji: "👃" },
            { id: "blank", label: "Blank pages only", emoji: "⬜" },
          ],
          correctId: "words",
          explanation: "Writers share adventures and facts through reading!",
        },
        {
          id: "q4",
          question: "Sign language helps people who…",
          options: [
            { id: "deaf", label: "Are deaf or hard of hearing talk with hands", emoji: "🤟" },
            { id: "sleep", label: "Are always sleeping", emoji: "😴" },
            { id: "fly", label: "Can fly", emoji: "🦅" },
            { id: "plants", label: "Are plants", emoji: "🌱" },
          ],
          correctId: "deaf",
          explanation: "Sign language is a beautiful language using hands and expressions!",
        },
      ],
    },
  },
  {
    id: "comm-odd-out",
    zoneId: "communication",
    type: "odd_one_out",
    title: "Odd Communication Out",
    description: "Which one doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong!",
      rounds: [
        { id: "r1", category: "ways to communicate", items: [{ id: "phone", label: "Phone", emoji: "📱" }, { id: "letter", label: "Letter", emoji: "✉️" }, { id: "tv", label: "TV", emoji: "📺" }, { id: "rock", label: "Rock", emoji: "🪨" }], oddId: "rock", explanation: "A rock can't send messages — it's not a way to communicate!" },
        { id: "r2", category: "things that make sound", items: [{ id: "bell", label: "Bell", emoji: "🔔" }, { id: "drum", label: "Drum", emoji: "🥁" }, { id: "whistle", label: "Whistle", emoji: "🎵" }, { id: "pillow", label: "Pillow", emoji: "🛏️" }], oddId: "pillow", explanation: "A pillow is soft and quiet — it doesn't make sound!" },
        { id: "r3", category: "things you can read", items: [{ id: "book", label: "Book", emoji: "📖" }, { id: "newspaper", label: "Newspaper", emoji: "📰" }, { id: "sign", label: "Sign", emoji: "🪧" }, { id: "ball", label: "Ball", emoji: "⚽" }], oddId: "ball", explanation: "You can't read a ball — it has no words on it!" },
      ],
    },
  },
  {
    id: "comm-true-false",
    zoneId: "communication",
    type: "true_false",
    title: "Communication Facts",
    description: "True or false about communication?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this communication fact true or false?",
      questions: [
        { id: "tf1", statement: "A telephone lets you talk to people far away", emoji: "📞", isTrue: true, explanation: "Yes! Phones help us talk to people even in other countries." },
        { id: "tf2", statement: "Dogs can read books", emoji: "🐕", isTrue: false, explanation: "No! Dogs can't read — only people can read books." },
        { id: "tf3", statement: "Sign language uses hands to talk", emoji: "🤟", isTrue: true, explanation: "Correct! People who can't hear use their hands to communicate." },
        { id: "tf4", statement: "Letters are sent through the internet", emoji: "✉️", isTrue: false, explanation: "Paper letters go by post/mail — emails go through the internet!" },
      ],
    },
  },
];
