import type { GameConfig } from "../../types";

export const foodGames: GameConfig[] = [
  {
    id: "food-nutrient-groups-sort",
    zoneId: "food",
    type: "drag_sort",
    title: "Energy, body-building, protective",
    description: "Food and Health — like Sarat’s balanced diet in your book.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Energy foods give power to work and play. Body-building foods help you grow strong. Protective foods (fruits and vegetables) help you stay well. Sort!",
      categories: [
        { id: "energy", label: "Energy-giving", emoji: "🍚" },
        { id: "body", label: "Body-building", emoji: "🥛" },
        { id: "protect", label: "Protective", emoji: "🥕" },
      ],
      items: [
        { id: "rice", label: "Rice", emoji: "🍚", category: "energy" },
        { id: "chapati", label: "Chapatti", emoji: "🫓", category: "energy" },
        { id: "bread", label: "Bread", emoji: "🍞", category: "energy" },
        { id: "butter", label: "Butter", emoji: "🧈", category: "energy" },
        { id: "milk", label: "Milk", emoji: "🥛", category: "body" },
        { id: "egg", label: "Eggs", emoji: "🥚", category: "body" },
        { id: "dal", label: "Dal (pulses)", emoji: "🫘", category: "body" },
        { id: "apple", label: "Apple", emoji: "🍎", category: "protect" },
        { id: "carrot", label: "Carrot", emoji: "🥕", category: "protect" },
        { id: "spinach", label: "Spinach", emoji: "🥬", category: "protect" },
      ],
    },
  },
  {
    id: "food-book-mcq",
    zoneId: "food",
    type: "picture_quiz",
    title: "Food and health check",
    description: "Questions in the style of your textbook exercises.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Tick the best answer — like your class exercises.",
      questions: [
        {
          id: "f1",
          question: "Which of these foods gives us energy?",
          options: [
            { id: "egg", label: "Eggs", emoji: "🥚" },
            { id: "milk", label: "Milk", emoji: "🥛" },
            { id: "rice", label: "Rice", emoji: "🍚" },
            { id: "apple", label: "Apple", emoji: "🍎" },
          ],
          correctId: "rice",
          explanation: "Rice, bread and chapatti are energy-giving foods in your book.",
        },
        {
          id: "f2",
          question: "Which of these is a junk food?",
          options: [
            { id: "apple", label: "Apple", emoji: "🍎" },
            { id: "brinjal", label: "Brinjal", emoji: "🍆" },
            { id: "burger", label: "Burger", emoji: "🍔" },
            { id: "dal", label: "Dal", emoji: "🫘" },
          ],
          correctId: "burger",
          explanation: "Fast foods like burgers and chips are junk — eat them only sometimes.",
        },
        {
          id: "f3",
          question: "Which food helps protect us from falling sick?",
          options: [
            { id: "butter", label: "Butter", emoji: "🧈" },
            { id: "cheese", label: "Cheese", emoji: "🧀" },
            { id: "fruit", label: "Fruit", emoji: "🍊" },
            { id: "sugar", label: "Sugar", emoji: "🍬" },
          ],
          correctId: "fruit",
          explanation: "Fruits and vegetables are protective foods.",
        },
      ],
    },
  },
  {
    id: "food-healthy-junk-sort",
    zoneId: "food",
    type: "drag_sort",
    title: "Healthy vs Junk",
    description: "Learn which foods help your body grow strong!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Sort foods into healthy treats and sometimes-junk foods!",
      categories: [
        { id: "healthy", label: "Healthy", emoji: "🥗" },
        { id: "junk", label: "Junk / Sometimes Food", emoji: "🍟" },
      ],
      items: [
        { id: "apple", label: "Apple", emoji: "🍎", category: "healthy" },
        { id: "broccoli", label: "Broccoli", emoji: "🥦", category: "healthy" },
        { id: "carrot", label: "Carrot", emoji: "🥕", category: "healthy" },
        { id: "milk", label: "Milk", emoji: "🥛", category: "healthy" },
        { id: "candy", label: "Candy", emoji: "🍬", category: "junk" },
        { id: "chips", label: "Chips", emoji: "🥔", category: "junk" },
        { id: "soda", label: "Soda", emoji: "🥤", category: "junk" },
        { id: "banana", label: "Banana", emoji: "🍌", category: "healthy" },
      ],
    },
  },
  {
    id: "food-where-grows-quiz",
    zoneId: "food",
    type: "picture_quiz",
    title: "Where Does It Grow?",
    description: "Do fruits and veggies grow on trees, under the ground, or on vines?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Think about where this yummy food grows!",
      questions: [
        {
          id: "q1",
          question: "Where do carrots usually grow?",
          options: [
            { id: "tree", label: "On a tree", emoji: "🌳" },
            { id: "underground", label: "Under the ground", emoji: "🥕" },
            { id: "water", label: "In the ocean", emoji: "🌊" },
            { id: "sky", label: "In the sky", emoji: "☁️" },
          ],
          correctId: "underground",
          explanation: "Carrots are root vegetables — they grow hidden under the soil!",
        },
        {
          id: "q2",
          question: "Where do apples usually grow?",
          options: [
            { id: "bush", label: "On a bush", emoji: "🌿" },
            { id: "tree", label: "On a tree", emoji: "🍎" },
            { id: "sand", label: "In the sand", emoji: "🏖️" },
            { id: "vine", label: "On a vine on the ground", emoji: "🍉" },
          ],
          correctId: "tree",
          explanation: "Apples hang from branches on apple trees!",
        },
        {
          id: "q3",
          question: "Where do grapes usually grow?",
          options: [
            { id: "tree", label: "On a tall tree", emoji: "🌲" },
            { id: "vine", label: "On a vine", emoji: "🍇" },
            { id: "underground", label: "Under the ground", emoji: "🥔" },
            { id: "lake", label: "In a lake", emoji: "🏞️" },
          ],
          correctId: "vine",
          explanation: "Grapes grow in bunches on grapevines!",
        },
        {
          id: "q4",
          question: "Where do potatoes grow?",
          options: [
            { id: "tree", label: "On a tree", emoji: "🌳" },
            { id: "underground", label: "Under the ground", emoji: "🥔" },
            { id: "water", label: "Floating on water", emoji: "💧" },
            { id: "flower", label: "Inside a flower", emoji: "🌸" },
          ],
          correctId: "underground",
          explanation: "Potatoes are tubers — they grow under the soil like buried treasure!",
        },
      ],
    },
  },
  {
    id: "food-groups-match",
    zoneId: "food",
    type: "memory_match",
    title: "Food Groups Match",
    description: "Match each food with its food group!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Find pairs that belong to the same idea — fruits, veggies, grains, and more!",
      pairs: [
        { id: "fruits", front: "Fruits", emoji: "🍎" },
        { id: "veggies", front: "Vegetables", emoji: "🥦" },
        { id: "grains", front: "Grains", emoji: "🍞" },
        { id: "protein", front: "Protein", emoji: "🥚" },
        { id: "dairy", front: "Dairy", emoji: "🧀" },
        { id: "water", front: "Water", emoji: "💧" },
      ],
    },
  },
  {
    id: "food-odd-out",
    zoneId: "food",
    type: "odd_one_out",
    title: "Odd Food Out",
    description: "Which food doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong with the others!",
      rounds: [
        { id: "r1", category: "fruits", items: [{ id: "apple", label: "Apple", emoji: "🍎" }, { id: "banana", label: "Banana", emoji: "🍌" }, { id: "grapes", label: "Grapes", emoji: "🍇" }, { id: "chair", label: "Chair", emoji: "🪑" }], oddId: "chair", explanation: "A chair isn't food — you sit on it!" },
        { id: "r2", category: "vegetables", items: [{ id: "carrot", label: "Carrot", emoji: "🥕" }, { id: "broccoli", label: "Broccoli", emoji: "🥦" }, { id: "ball", label: "Ball", emoji: "⚽" }, { id: "corn", label: "Corn", emoji: "🌽" }], oddId: "ball", explanation: "A ball is a toy, not a vegetable!" },
        { id: "r3", category: "drinks", items: [{ id: "milk", label: "Milk", emoji: "🥛" }, { id: "juice", label: "Juice", emoji: "🧃" }, { id: "water", label: "Water", emoji: "💧" }, { id: "shoe", label: "Shoe", emoji: "👟" }], oddId: "shoe", explanation: "You can't drink a shoe!" },
        { id: "r4", category: "healthy foods", items: [{ id: "salad", label: "Salad", emoji: "🥗" }, { id: "apple2", label: "Apple", emoji: "🍎" }, { id: "candy", label: "Candy", emoji: "🍬" }, { id: "carrot2", label: "Carrot", emoji: "🥕" }], oddId: "candy", explanation: "Candy is a treat, not a healthy food!" },
      ],
    },
  },
  {
    id: "food-true-false",
    zoneId: "food",
    type: "true_false",
    title: "Food Facts: True or False?",
    description: "Test your food knowledge!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this food fact true or false?",
      questions: [
        { id: "tf1", statement: "Carrots are orange", emoji: "🥕", isTrue: true, explanation: "Yes! Most carrots are bright orange." },
        { id: "tf2", statement: "Ice cream is a vegetable", emoji: "🍦", isTrue: false, explanation: "No! Ice cream is a frozen dessert, not a veggie!" },
        { id: "tf3", statement: "Milk comes from cows", emoji: "🐄", isTrue: true, explanation: "That's right! Cows give us milk." },
        { id: "tf4", statement: "Bananas grow underground", emoji: "🍌", isTrue: false, explanation: "Nope! Bananas grow on tall plants above ground." },
        { id: "tf5", statement: "Water is important for your body", emoji: "💧", isTrue: true, explanation: "Yes! Your body needs water every day to stay healthy." },
      ],
    },
  },
];
