import type { GameConfig } from "../../types";

export const healthSafetyGames: GameConfig[] = [
  {
    id: "health-good-habits-quiz",
    zoneId: "health-safety",
    type: "picture_quiz",
    title: "Good Habits",
    description: "Healthy habits keep your body happy!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Which choice is a super healthy habit?",
      questions: [
        {
          id: "q1",
          question: "How do we keep our teeth strong and shiny?",
          options: [
            { id: "never", label: "Never brush", emoji: "🚫" },
            { id: "brush", label: "Brush teeth morning & night", emoji: "🪥" },
            { id: "candy-only", label: "Only eat candy", emoji: "🍬" },
            { id: "mud", label: "Rinse with mud", emoji: "🟤" },
          ],
          correctId: "brush",
          explanation: "Brushing chases away sugar bugs and keeps smiles bright!",
        },
        {
          id: "q2",
          question: "When should you wash your hands?",
          options: [
            { id: "never", label: "Never", emoji: "🙅" },
            { id: "before-after", label: "Before eating & after the toilet", emoji: "🧼" },
            { id: "only-rain", label: "Only in rain", emoji: "🌧️" },
            { id: "midnight-only", label: "Only at midnight", emoji: "🕛" },
          ],
          correctId: "before-after",
          explanation: "Clean hands stop germs from getting into our mouths!",
        },
        {
          id: "q3",
          question: "Why do we sleep enough at night?",
          options: [
            { id: "grow", label: "To grow and feel rested", emoji: "😴" },
            { id: "skip", label: "To skip breakfast", emoji: "🚫" },
            { id: "hide", label: "To hide toys", emoji: "🧸" },
            { id: "tv", label: "To watch TV all night", emoji: "📺" },
          ],
          correctId: "grow",
          explanation: "Sleep is when your body repairs and your brain sorts the day!",
        },
        {
          id: "q4",
          question: "What helps your body after running and playing?",
          options: [
            { id: "water", label: "Drinking water", emoji: "💧" },
            { id: "hot-sauce", label: "Hot sauce", emoji: "🌶️" },
            { id: "skip-meal", label: "Skipping all meals", emoji: "🚫" },
            { id: "couch", label: "Never moving again", emoji: "🛋️" },
          ],
          correctId: "water",
          explanation: "Water replaces what you sweat out and keeps muscles happy!",
        },
      ],
    },
  },
  {
    id: "health-safety-signs-match",
    zoneId: "health-safety",
    type: "memory_match",
    title: "Safety Signs",
    description: "Match safety signs and what they mean!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Find pairs of safety ideas!",
      pairs: [
        { id: "stop", front: "Stop", emoji: "🛑" },
        { id: "crosswalk", front: "Crosswalk", emoji: "🚸" },
        { id: "fire", front: "Fire exit", emoji: "🚪" },
        { id: "helmet", front: "Wear helmet", emoji: "⛑️" },
        { id: "danger", front: "Danger zone", emoji: "⚠️" },
        { id: "first-aid", front: "First aid", emoji: "🩹" },
      ],
    },
  },
  {
    id: "health-daily-routine-sequence",
    zoneId: "health-safety",
    type: "sequence_builder",
    title: "Daily Routine",
    description: "Order a healthy day from morning to night!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "What usually comes first in a good day?",
      steps: [
        { id: "wake", label: "Wake up & stretch", emoji: "🌅", order: 1 },
        { id: "wash", label: "Wash face & brush teeth", emoji: "🪥", order: 2 },
        { id: "breakfast", label: "Eat breakfast", emoji: "🥣", order: 3 },
        { id: "school", label: "School or play & learn", emoji: "🎒", order: 4 },
        { id: "play", label: "Play outside safely", emoji: "⚽", order: 5 },
        { id: "sleep", label: "Bath, story, sleep", emoji: "🌙", order: 6 },
      ],
    },
  },
  {
    id: "hs-odd-out",
    zoneId: "health-safety",
    type: "odd_one_out",
    title: "Odd Safety Out",
    description: "Which one doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong!",
      rounds: [
        { id: "r1", category: "healthy habits", items: [{ id: "brush", label: "Brush teeth", emoji: "🪥" }, { id: "wash", label: "Wash hands", emoji: "🧼" }, { id: "sleep", label: "Sleep well", emoji: "😴" }, { id: "candy", label: "Eat lots of candy", emoji: "🍬" }], oddId: "candy", explanation: "Eating lots of candy isn't healthy — it gives you cavities!" },
        { id: "r2", category: "safety gear", items: [{ id: "helmet", label: "Helmet", emoji: "⛑️" }, { id: "seatbelt", label: "Seatbelt", emoji: "🔒" }, { id: "goggles", label: "Goggles", emoji: "🥽" }, { id: "teddy", label: "Teddy Bear", emoji: "🧸" }], oddId: "teddy", explanation: "A teddy bear is a toy — it doesn't keep you safe!" },
        { id: "r3", category: "ways to stay healthy", items: [{ id: "exercise", label: "Exercise", emoji: "🏃" }, { id: "fruit", label: "Eat fruit", emoji: "🍎" }, { id: "water", label: "Drink water", emoji: "💧" }, { id: "tv", label: "Watch TV all day", emoji: "📺" }], oddId: "tv", explanation: "Watching TV all day isn't healthy — your body needs to move!" },
      ],
    },
  },
  {
    id: "hs-true-false",
    zoneId: "health-safety",
    type: "true_false",
    title: "Health Facts: True or False?",
    description: "Test your health knowledge!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this health fact true or false?",
      questions: [
        { id: "tf1", statement: "Washing hands stops germs from spreading", emoji: "🧼", isTrue: true, explanation: "Yes! Clean hands keep germs away." },
        { id: "tf2", statement: "You should cross the road without looking", emoji: "🚶", isTrue: false, explanation: "No! Always look both ways before crossing the road." },
        { id: "tf3", statement: "Exercise makes your body stronger", emoji: "💪", isTrue: true, explanation: "Correct! Running, jumping, and playing make you fit and strong." },
        { id: "tf4", statement: "You should eat only sweets every day", emoji: "🍭", isTrue: false, explanation: "No! You need vegetables, fruits, and protein to grow healthy." },
      ],
    },
  },
];
