import type { GameConfig } from "../../types";

export const neighbourhoodGames: GameConfig[] = [
  {
    id: "neighbourhood-waste-sort",
    zoneId: "neighbourhood",
    type: "drag_sort",
    title: "Clean the stuff",
    description: "Eco Smart — sort waste the way your activity sheet shows.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Compost food scraps, recycle bottles and cans, paper in its bin, trash that cannot be recycled, and reusable things for charity.",
      categories: [
        { id: "compost", label: "Compost", emoji: "🪣" },
        { id: "can", label: "Bottles & cans", emoji: "♻️" },
        { id: "trash", label: "Garbage", emoji: "🗑️" },
        { id: "paper", label: "Paper & cardboard", emoji: "📦" },
        { id: "charity", label: "Charity / reuse", emoji: "📚" },
      ],
      items: [
        { id: "core", label: "Apple core", emoji: "🍎", category: "compost" },
        { id: "bread", label: "Bread scraps", emoji: "🍞", category: "compost" },
        { id: "bottle", label: "Glass bottle", emoji: "🍾", category: "can" },
        { id: "can1", label: "Metal drink can", emoji: "🥫", category: "can" },
        { id: "chip", label: "Crisp / chip packet", emoji: "🍟", category: "trash" },
        { id: "balloon", label: "Burst balloons", emoji: "🎈", category: "trash" },
        { id: "card", label: "Cardboard box", emoji: "📦", category: "paper" },
        { id: "paper1", label: "Old worksheets", emoji: "📄", category: "paper" },
        { id: "book", label: "Story book to share", emoji: "📖", category: "charity" },
        { id: "shirt", label: "Shirt that still fits someone else", emoji: "👕", category: "charity" },
      ],
    },
  },
  {
    id: "neighbourhood-places-quiz",
    zoneId: "neighbourhood",
    type: "picture_quiz",
    title: "Places Around Us",
    description: "Know the special places in your town!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Where would you go for each need?",
      questions: [
        {
          id: "q1",
          question: "Where do you go when you are very sick and need a doctor?",
          options: [
            { id: "park", label: "Park", emoji: "🌳" },
            { id: "hospital", label: "Hospital", emoji: "🏥" },
            { id: "bakery", label: "Bakery", emoji: "🥐" },
            { id: "zoo", label: "Zoo", emoji: "🦁" },
          ],
          correctId: "hospital",
          explanation: "Hospitals and clinics have doctors and nurses to help you heal!",
        },
        {
          id: "q2",
          question: "Where do children learn reading and math together?",
          options: [
            { id: "school", label: "School", emoji: "🏫" },
            { id: "pool", label: "Swimming pool", emoji: "🏊" },
            { id: "farm", label: "Farm only", emoji: "🚜" },
            { id: "moon", label: "The moon", emoji: "🌙" },
          ],
          correctId: "school",
          explanation: "School is where teachers and friends learn with you every day!",
        },
        {
          id: "q3",
          question: "Where can you buy fruits, veggies, and food from sellers?",
          options: [
            { id: "market", label: "Market / shop", emoji: "🛒" },
            { id: "desert", label: "Desert", emoji: "🏜️" },
            { id: "volcano", label: "Volcano", emoji: "🌋" },
            { id: "cloud", label: "On a cloud", emoji: "☁️" },
          ],
          correctId: "market",
          explanation: "Markets and stores are where families buy fresh food!",
        },
        {
          id: "q4",
          question: "Where can you play on swings and slides outdoors?",
          options: [
            { id: "park", label: "Park", emoji: "🛝" },
            { id: "office", label: "Office desk", emoji: "💼" },
            { id: "elevator", label: "Elevator", emoji: "🛗" },
            { id: "closet", label: "Tiny closet", emoji: "🚪" },
          ],
          correctId: "park",
          explanation: "Parks are green spaces for play, walks, and picnics!",
        },
      ],
    },
  },
  {
    id: "neighbourhood-helpers-match",
    zoneId: "neighbourhood",
    type: "memory_match",
    title: "Community Helpers",
    description: "Match helpers with their neighborhood jobs!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Flip and match community heroes!",
      pairs: [
        { id: "baker", front: "Baker", emoji: "🥖" },
        { id: "garbage", front: "Garbage collector", emoji: "🗑️" },
        { id: "librarian", front: "Librarian", emoji: "📚" },
        { id: "crossing", front: "Crossing guard", emoji: "🚸" },
        { id: "mail", front: "Mail carrier", emoji: "📬" },
        { id: "vet", front: "Vet", emoji: "🐾" },
      ],
    },
  },
  {
    id: "neighbourhood-school-sequence",
    zoneId: "neighbourhood",
    type: "sequence_builder",
    title: "Going to School",
    description: "Put the morning trip to school in order!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "What happens on a school morning?",
      steps: [
        { id: "wake", label: "Wake up", emoji: "⏰", order: 1 },
        { id: "dress", label: "Get dressed & pack bag", emoji: "🎒", order: 2 },
        { id: "breakfast", label: "Eat breakfast", emoji: "🥞", order: 3 },
        { id: "travel", label: "Walk, bus, or car to school", emoji: "🚌", order: 4 },
        { id: "gate", label: "Arrive at school gate", emoji: "🏫", order: 5 },
        { id: "class", label: "Hello, classroom!", emoji: "👋", order: 6 },
      ],
    },
  },
  {
    id: "neigh-odd-out",
    zoneId: "neighbourhood",
    type: "odd_one_out",
    title: "Odd Place Out",
    description: "Which place doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong!",
      rounds: [
        { id: "r1", category: "places in a neighbourhood", items: [{ id: "school", label: "School", emoji: "🏫" }, { id: "park", label: "Park", emoji: "🏞️" }, { id: "hospital", label: "Hospital", emoji: "🏥" }, { id: "moon", label: "Moon", emoji: "🌙" }], oddId: "moon", explanation: "The moon is in space — it's not in your neighbourhood!" },
        { id: "r2", category: "people who help us", items: [{ id: "police", label: "Police", emoji: "👮" }, { id: "postman", label: "Postman", emoji: "📮" }, { id: "teacher", label: "Teacher", emoji: "👩‍🏫" }, { id: "cloud", label: "Cloud", emoji: "☁️" }], oddId: "cloud", explanation: "A cloud isn't a person — it's in the sky!" },
        { id: "r3", category: "things in a park", items: [{ id: "swing", label: "Swing", emoji: "🎠" }, { id: "bench", label: "Bench", emoji: "🪑" }, { id: "tree", label: "Tree", emoji: "🌳" }, { id: "fridge", label: "Fridge", emoji: "🧊" }], oddId: "fridge", explanation: "A fridge belongs in a kitchen, not in a park!" },
      ],
    },
  },
  {
    id: "neigh-true-false",
    zoneId: "neighbourhood",
    type: "true_false",
    title: "Neighbourhood Facts",
    description: "True or false?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this fact true or false?",
      questions: [
        { id: "tf1", statement: "A post office helps send letters", emoji: "📮", isTrue: true, explanation: "Yes! You go to the post office to mail letters and packages." },
        { id: "tf2", statement: "We can swim in the library", emoji: "📚", isTrue: false, explanation: "No! Libraries are for reading books, not swimming!" },
        { id: "tf3", statement: "Parks have trees and playgrounds", emoji: "🏞️", isTrue: true, explanation: "Correct! Parks are fun places with nature and play areas." },
        { id: "tf4", statement: "Hospitals help sick people", emoji: "🏥", isTrue: true, explanation: "Yes! Doctors and nurses work in hospitals to help people feel better." },
      ],
    },
  },
];
