import type { GameConfig } from "../../types";

export const othersGames: GameConfig[] = [
  {
    id: "others-minerals-match",
    zoneId: "others-in-my-world",
    type: "memory_match",
    title: "Minerals in daily life",
    description: "Rocks and Minerals — what things are made of.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction:
        "Your book links talc to powder, graphite to pencil lead, diamond to jewellery, and more. Find the pairs!",
      pairs: [
        { id: "talc", front: "Talc → powder", emoji: "🧴" },
        { id: "graphite", front: "Graphite → pencil", emoji: "✏️" },
        { id: "diamond", front: "Diamond → jewellery", emoji: "💎" },
        { id: "clay", front: "China clay → pot", emoji: "🏺" },
        { id: "gypsum", front: "Gypsum → chalk", emoji: "🖍️" },
        { id: "tungsten", front: "Tungsten → bulb part", emoji: "💡" },
      ],
    },
  },
  {
    id: "others-who-helps-quiz",
    zoneId: "others-in-my-world",
    type: "picture_quiz",
    title: "Who Helps Us?",
    description: "Learn about people who help in our community!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Who does this important job? Pick the right helper!",
      questions: [
        {
          id: "q1",
          question: "Who brings letters and packages to your home?",
          options: [
            { id: "doctor", label: "Doctor", emoji: "🩺" },
            { id: "postman", label: "Postman", emoji: "📮" },
            { id: "chef", label: "Chef", emoji: "👨‍🍳" },
            { id: "pilot", label: "Pilot", emoji: "✈️" },
          ],
          correctId: "postman",
          explanation: "The postman delivers mail and packages so we can get letters from friends!",
        },
        {
          id: "q2",
          question: "Who helps you when you feel sick?",
          options: [
            { id: "teacher", label: "Teacher", emoji: "👩‍🏫" },
            { id: "doctor", label: "Doctor", emoji: "🩺" },
            { id: "farmer", label: "Farmer", emoji: "👨‍🌾" },
            { id: "artist", label: "Artist", emoji: "🎨" },
          ],
          correctId: "doctor",
          explanation: "Doctors and nurses help us stay healthy and feel better!",
        },
        {
          id: "q3",
          question: "Who teaches you new things at school?",
          options: [
            { id: "firefighter", label: "Firefighter", emoji: "🧑‍🚒" },
            { id: "teacher", label: "Teacher", emoji: "👩‍🏫" },
            { id: "driver", label: "Bus Driver", emoji: "🚌" },
            { id: "baker", label: "Baker", emoji: "🥖" },
          ],
          correctId: "teacher",
          explanation: "Teachers help us read, count, and discover the world!",
        },
        {
          id: "q4",
          question: "Who puts out fires and keeps us safe from fire?",
          options: [
            { id: "police", label: "Police", emoji: "👮" },
            { id: "librarian", label: "Librarian", emoji: "📚" },
            { id: "firefighter", label: "Firefighter", emoji: "🧑‍🚒" },
            { id: "gardener", label: "Gardener", emoji: "🌻" },
          ],
          correctId: "firefighter",
          explanation: "Firefighters are brave helpers who stop fires and rescue people!",
        },
      ],
    },
  },
  {
    id: "others-family-sort",
    zoneId: "others-in-my-world",
    type: "drag_sort",
    title: "My Family",
    description: "Sort who is in your family and who is a friend or neighbor!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Is this person usually in your family, or not? Sort each one!",
      categories: [
        { id: "family", label: "Family", emoji: "👨‍👩‍👧" },
        { id: "not-family", label: "Not Family", emoji: "🤝" },
      ],
      items: [
        { id: "mom", label: "Mom", emoji: "👩", category: "family" },
        { id: "dad", label: "Dad", emoji: "👨", category: "family" },
        { id: "sister", label: "Sister", emoji: "👧", category: "family" },
        { id: "grandma", label: "Grandma", emoji: "👵", category: "family" },
        { id: "classmate", label: "Classmate", emoji: "🧒", category: "not-family" },
        { id: "neighbor", label: "Neighbor", emoji: "🏠", category: "not-family" },
        { id: "teacher", label: "Teacher", emoji: "👩‍🏫", category: "not-family" },
        { id: "cousin", label: "Cousin", emoji: "🧑", category: "family" },
      ],
    },
  },
  {
    id: "others-helpers-match",
    zoneId: "others-in-my-world",
    type: "memory_match",
    title: "Community Helpers Match",
    description: "Match each helper with their tool or vehicle!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Flip the cards and find matching pairs of helpers!",
      pairs: [
        { id: "doctor", front: "Doctor", emoji: "🩺" },
        { id: "nurse", front: "Nurse", emoji: "💉" },
        { id: "police", front: "Police", emoji: "🚓" },
        { id: "firefighter", front: "Firefighter", emoji: "🚒" },
        { id: "teacher", front: "Teacher", emoji: "📖" },
        { id: "postman", front: "Postman", emoji: "📬" },
      ],
    },
  },
  {
    id: "others-odd-out",
    zoneId: "others-in-my-world",
    type: "odd_one_out",
    title: "Odd Helper Out",
    description: "Which one doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong!",
      rounds: [
        { id: "r1", category: "community helpers", items: [{ id: "doctor", label: "Doctor", emoji: "👨‍⚕️" }, { id: "teacher", label: "Teacher", emoji: "👩‍🏫" }, { id: "firefighter", label: "Firefighter", emoji: "👨‍🚒" }, { id: "ice-cream", label: "Ice Cream", emoji: "🍦" }], oddId: "ice-cream", explanation: "Ice cream is a treat, not a community helper!" },
        { id: "r2", category: "family members", items: [{ id: "mom", label: "Mom", emoji: "👩" }, { id: "dad", label: "Dad", emoji: "👨" }, { id: "sister", label: "Sister", emoji: "👧" }, { id: "car", label: "Car", emoji: "🚗" }], oddId: "car", explanation: "A car is a vehicle — it's not a family member!" },
        { id: "r3", category: "pets", items: [{ id: "dog", label: "Dog", emoji: "🐕" }, { id: "cat", label: "Cat", emoji: "🐈" }, { id: "fish", label: "Fish", emoji: "🐟" }, { id: "chair", label: "Chair", emoji: "🪑" }], oddId: "chair", explanation: "A chair is furniture — it's not a pet!" },
      ],
    },
  },
  {
    id: "others-true-false",
    zoneId: "others-in-my-world",
    type: "true_false",
    title: "People Around Us: Facts",
    description: "True or false?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this fact true or false?",
      questions: [
        { id: "tf1", statement: "A doctor helps sick people get better", emoji: "👨‍⚕️", isTrue: true, explanation: "Yes! Doctors take care of us when we're not feeling well." },
        { id: "tf2", statement: "Teachers fly airplanes", emoji: "👩‍🏫", isTrue: false, explanation: "No! Teachers teach us in school — pilots fly airplanes." },
        { id: "tf3", statement: "Friends share and play together", emoji: "🤝", isTrue: true, explanation: "That's right! Good friends share and have fun together." },
        { id: "tf4", statement: "A pet rock needs to eat food", emoji: "🪨", isTrue: false, explanation: "No! Rocks don't eat — only living things need food." },
      ],
    },
  },
];
