import type { GameConfig } from "../../types";

export const plantsGames: GameConfig[] = [
  {
    id: "plants-parts-quiz",
    zoneId: "plants",
    type: "picture_quiz",
    title: "Parts of a Plant",
    description: "Can you name the parts of a plant?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Look at the picture and choose the right answer!",
      questions: [
        {
          id: "q1",
          question: "Which part of the plant takes in water from the soil?",
          options: [
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "flower", label: "Flower", emoji: "🌸" },
            { id: "stem", label: "Stem", emoji: "🌿" },
          ],
          correctId: "root",
          explanation: "Roots grow underground and suck up water like a straw!",
        },
        {
          id: "q2",
          question: "Which part holds the plant up straight?",
          options: [
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "stem", label: "Stem", emoji: "🌿" },
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "fruit", label: "Fruit", emoji: "🍎" },
          ],
          correctId: "stem",
          explanation: "The stem is like the plant's backbone — it holds everything up!",
        },
        {
          id: "q3",
          question: "Which part of the plant makes food using sunlight?",
          options: [
            { id: "flower", label: "Flower", emoji: "🌸" },
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "seed", label: "Seed", emoji: "🫘" },
          ],
          correctId: "leaf",
          explanation: "Leaves are like tiny kitchens — they use sunlight to cook food for the plant!",
        },
        {
          id: "q4",
          question: "What does a seed grow into?",
          options: [
            { id: "rock", label: "Rock", emoji: "🪨" },
            { id: "plant", label: "New Plant", emoji: "🌱" },
            { id: "water", label: "Water", emoji: "💧" },
            { id: "cloud", label: "Cloud", emoji: "☁️" },
          ],
          correctId: "plant",
          explanation: "A tiny seed has a baby plant inside it, waiting to grow!",
        },
      ],
    },
  },
  {
    id: "plants-sort",
    zoneId: "plants",
    type: "drag_sort",
    title: "Plant or Not a Plant?",
    description: "Sort items into plants and not-plants!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Is it a plant? Sort each item into the right group!",
      categories: [
        { id: "plant", label: "Plants", emoji: "🌿" },
        { id: "not-plant", label: "Not a Plant", emoji: "🚫" },
      ],
      items: [
        { id: "tree", label: "Tree", emoji: "🌳", category: "plant" },
        { id: "rose", label: "Rose", emoji: "🌹", category: "plant" },
        { id: "grass", label: "Grass", emoji: "🌾", category: "plant" },
        { id: "cactus", label: "Cactus", emoji: "🌵", category: "plant" },
        { id: "rock", label: "Rock", emoji: "🪨", category: "not-plant" },
        { id: "car", label: "Car", emoji: "🚗", category: "not-plant" },
        { id: "chair", label: "Chair", emoji: "🪑", category: "not-plant" },
        { id: "sunflower", label: "Sunflower", emoji: "🌻", category: "plant" },
      ],
    },
  },
  {
    id: "plants-match",
    zoneId: "plants",
    type: "memory_match",
    title: "Plant & Fruit Match",
    description: "Match each plant with its fruit!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Flip the cards and find matching pairs!",
      pairs: [
        { id: "apple", front: "Apple Tree", emoji: "🍎" },
        { id: "banana", front: "Banana Plant", emoji: "🍌" },
        { id: "coconut", front: "Coconut Palm", emoji: "🥥" },
        { id: "orange", front: "Orange Tree", emoji: "🍊" },
        { id: "mango", front: "Mango Tree", emoji: "🥭" },
        { id: "grape", front: "Grape Vine", emoji: "🍇" },
      ],
    },
  },
  {
    id: "plants-sequence",
    zoneId: "plants",
    type: "sequence_builder",
    title: "Seed to Flower",
    description: "Put the steps of plant growth in order!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "Arrange the steps to show how a plant grows!",
      steps: [
        { id: "seed", label: "Plant a seed", emoji: "🫘", order: 1 },
        { id: "water", label: "Water it", emoji: "💧", order: 2 },
        { id: "sprout", label: "Sprout appears", emoji: "🌱", order: 3 },
        { id: "grow", label: "Stem grows tall", emoji: "🌿", order: 4 },
        { id: "bud", label: "Bud forms", emoji: "🌷", order: 5 },
        { id: "flower", label: "Flower blooms!", emoji: "🌸", order: 6 },
      ],
    },
  },
  {
    id: "plants-spot-garden",
    zoneId: "plants",
    type: "spot_difference",
    title: "Garden Spot the Difference",
    description: "Find what changed in the garden!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "spot_difference",
      instruction: "Look at both gardens and find the differences!",
      imageA: "🌳 🌸 🌿 🌻 🌹 🍃 🌾 🌵 🌳",
      imageB: "🌳 🌺 🌿 🌻 🌷 🍃 🌾 🌵 🌳",
      differences: [
        { id: "d1", x: 33, y: 15, radius: 18, label: "Flower changed from 🌸 to 🌺" },
        { id: "d2", x: 68, y: 15, radius: 18, label: "Rose became a tulip 🌷" },
      ],
    },
  },
  {
    id: "plants-color-flower",
    zoneId: "plants",
    type: "color_activity",
    title: "Color the Flower",
    description: "Paint each part of the flower the right color!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "color_activity",
      instruction: "Pick the correct color for each part of the flower!",
      palette: ["#ef4444", "#22c55e", "#a16207", "#fbbf24", "#ec4899"],
      regions: [
        { id: "petals", label: "🌸 Petals", correctColor: "#ec4899", path: "" },
        { id: "stem", label: "🌿 Stem", correctColor: "#22c55e", path: "" },
        { id: "center", label: "🟡 Center", correctColor: "#fbbf24", path: "" },
        { id: "soil", label: "🟤 Soil", correctColor: "#a16207", path: "" },
      ],
    },
  },
];
