import type { GameConfig } from "../../types";

export const plantsGames: GameConfig[] = [
  {
    id: "plants-book-nep-how-we-learn",
    zoneId: "plants",
    type: "true_false",
    title: "How we learn science",
    description: "NEP Foundational Stage — play, puzzles and learning-by-doing.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction:
        "Your book says Foundational Stage (Grades I and II) should use play, puzzles, and doing things with your hands. Is each line true?",
      questions: [
        {
          id: "n1",
          statement:
            "Exploring and learning-by-doing, play-way method, observation, puzzles, logical thinking and problem-solving should be the methods involved in learning.",
          emoji: "🧩",
          isTrue: true,
          explanation: "That is what the Foundational Stage section says in your textbook.",
        },
        {
          id: "n2",
          statement: "Science class should only be about memorising long answers for exams.",
          emoji: "📚",
          isTrue: false,
          explanation:
            "NEP asks for conceptual understanding rather than only rote learning and exams.",
        },
        {
          id: "n3",
          statement: "Hands-on activity means actually doing an activity, not only watching a demo.",
          emoji: "✋",
          isTrue: true,
          explanation: "Learning-by-doing is doing the activity yourself.",
        },
      ],
    },
  },
  {
    id: "plants-eco-smart-three-rs",
    zoneId: "plants",
    type: "true_false",
    title: "Eco Smart — the Three Rs",
    description: "Reduce, reuse, recycle from your Eco Smart pages.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction:
        "Your book says children can help the environment. Decide if each sentence matches Eco Smart.",
      questions: [
        {
          id: "e1",
          statement: "Reduce means cutting down on garbage by buying only what we need.",
          emoji: "♻️",
          isTrue: true,
          explanation: "Reduce means less waste — buy only what you need.",
        },
        {
          id: "e2",
          statement: "Reuse means throwing everything away after one use.",
          emoji: "🗑️",
          isTrue: false,
          explanation: "Reuse means using something again instead of throwing it away.",
        },
        {
          id: "e3",
          statement: "Recycle means making new products from old materials.",
          emoji: "🔁",
          isTrue: true,
          explanation: "Recycle turns finished items into new useful things.",
        },
        {
          id: "e4",
          statement: "Plants purify and clean the air we breathe.",
          emoji: "🌳",
          isTrue: true,
          explanation: "Your book reminds us plants help keep air fresh.",
        },
      ],
    },
  },
  {
    id: "plants-ch1-types-sort",
    zoneId: "plants",
    type: "drag_sort",
    title: "Plant World — types of plants",
    description: "Trees, shrubs, herbs, climbers and creepers (Chapter 1).",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Trees are tall with a thick woody trunk. Shrubs are smaller with thin woody stems. Herbs are small with soft stems. Climbers coil around support. Creepers spread on the ground. Sort each plant!",
      categories: [
        { id: "tree", label: "Trees", emoji: "🌳" },
        { id: "shrub", label: "Shrubs", emoji: "🌺" },
        { id: "herb", label: "Herbs", emoji: "🌿" },
        { id: "climber", label: "Climbers", emoji: "🪴" },
        { id: "creeper", label: "Creepers", emoji: "🍉" },
      ],
      items: [
        { id: "banyan", label: "Banyan", emoji: "🌳", category: "tree" },
        { id: "mango-t", label: "Mango tree", emoji: "🥭", category: "tree" },
        { id: "rose", label: "Rose bush", emoji: "🌹", category: "shrub" },
        { id: "sunflower", label: "Sunflower", emoji: "🌻", category: "shrub" },
        { id: "mint", label: "Mint", emoji: "🌿", category: "herb" },
        { id: "spinach", label: "Spinach", emoji: "🥬", category: "herb" },
        { id: "grape", label: "Grapevine", emoji: "🍇", category: "climber" },
        { id: "money", label: "Money plant", emoji: "🪴", category: "climber" },
        { id: "melon", label: "Watermelon vine", emoji: "🍉", category: "creeper" },
        { id: "pumpkin", label: "Pumpkin vine", emoji: "🎃", category: "creeper" },
      ],
    },
  },
  {
    id: "plants-photosynthesis-facts",
    zoneId: "plants",
    type: "true_false",
    title: "Photosynthesis facts",
    description: "Green plants make their own food — from your book.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction:
        "Green plants need air, sunlight and water. Leaves make food. The process is called photosynthesis.",
      questions: [
        {
          id: "ph1",
          statement: "Green plants are the only living things that can make their own food.",
          emoji: "🍃",
          isTrue: true,
          explanation: "That is what your science book says.",
        },
        {
          id: "ph2",
          statement: "Plants get water from the soil through their roots.",
          emoji: "💧",
          isTrue: true,
          explanation: "Roots absorb water from the soil.",
        },
        {
          id: "ph3",
          statement: "Food for the plant is mainly made in the roots.",
          emoji: "🌱",
          isTrue: false,
          explanation: "Leaves make food using sunlight — not the roots.",
        },
      ],
    },
  },
  {
    id: "plants-ch2-part-we-eat",
    zoneId: "plants",
    type: "drag_sort",
    title: "Which part do we eat?",
    description: "Roots, stems, seeds, leaves, fruits — Plants are Useful.",
    difficulty: 2,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction:
        "Some plants store food in roots (carrot). Some stems are eaten (potato, ginger). Seeds give cereals and pulses. We eat leaves and fruits too. Sort!",
      categories: [
        { id: "root", label: "Root food", emoji: "🥕" },
        { id: "stem", label: "Stem food", emoji: "🥔" },
        { id: "seed", label: "Seeds / dal", emoji: "🫘" },
        { id: "leaf", label: "Leaves", emoji: "🥬" },
        { id: "fruit", label: "Fruits", emoji: "🍎" },
      ],
      items: [
        { id: "carrot", label: "Carrot", emoji: "🥕", category: "root" },
        { id: "beet", label: "Beetroot", emoji: "🟣", category: "root" },
        { id: "potato", label: "Potato", emoji: "🥔", category: "stem" },
        { id: "ginger", label: "Ginger", emoji: "🫚", category: "stem" },
        { id: "rice", label: "Rice (cereal)", emoji: "🍚", category: "seed" },
        { id: "gram", label: "Gram (pulse)", emoji: "🫘", category: "seed" },
        { id: "spinach2", label: "Spinach", emoji: "🥬", category: "leaf" },
        { id: "cabbage", label: "Cabbage", emoji: "🥬", category: "leaf" },
        { id: "mango", label: "Mango", emoji: "🥭", category: "fruit" },
        { id: "apple", label: "Apple", emoji: "🍎", category: "fruit" },
      ],
    },
  },
  {
    id: "plants-parts-quiz",
    zoneId: "plants",
    type: "picture_quiz",
    title: "Parts of a Plant",
    description: "Can you name the parts of a plant?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Look at the picture and choose the right answer!",
      questions: [
        {
          id: "q1",
          question: "Which part of the plant takes in water from the soil?",
          options: [
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "flower", label: "Flower", emoji: "🌸" },
            { id: "stem", label: "Stem", emoji: "🌿" },
          ],
          correctId: "root",
          explanation: "Roots grow underground and suck up water like a straw!",
        },
        {
          id: "q2",
          question: "Which part holds the plant up straight?",
          options: [
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "stem", label: "Stem", emoji: "🌿" },
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "fruit", label: "Fruit", emoji: "🍎" },
          ],
          correctId: "stem",
          explanation: "The stem is like the plant's backbone — it holds everything up!",
        },
        {
          id: "q3",
          question: "Which part of the plant makes food using sunlight?",
          options: [
            { id: "flower", label: "Flower", emoji: "🌸" },
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "seed", label: "Seed", emoji: "🫘" },
          ],
          correctId: "leaf",
          explanation: "Leaves are like tiny kitchens — they use sunlight to cook food for the plant!",
        },
        {
          id: "q4",
          question: "What does a seed grow into?",
          options: [
            { id: "rock", label: "Rock", emoji: "🪨" },
            { id: "plant", label: "New Plant", emoji: "🌱" },
            { id: "water", label: "Water", emoji: "💧" },
            { id: "cloud", label: "Cloud", emoji: "☁️" },
          ],
          correctId: "plant",
          explanation: "A tiny seed has a baby plant inside it, waiting to grow!",
        },
      ],
    },
  },
  {
    id: "plants-sort",
    zoneId: "plants",
    type: "drag_sort",
    title: "Plant or Not a Plant?",
    description: "Sort items into plants and not-plants!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "drag_sort",
      instruction: "Is it a plant? Sort each item into the right group!",
      categories: [
        { id: "plant", label: "Plants", emoji: "🌿" },
        { id: "not-plant", label: "Not a Plant", emoji: "🚫" },
      ],
      items: [
        { id: "tree", label: "Tree", emoji: "🌳", category: "plant" },
        { id: "rose", label: "Rose", emoji: "🌹", category: "plant" },
        { id: "grass", label: "Grass", emoji: "🌾", category: "plant" },
        { id: "cactus", label: "Cactus", emoji: "🌵", category: "plant" },
        { id: "rock", label: "Rock", emoji: "🪨", category: "not-plant" },
        { id: "car", label: "Car", emoji: "🚗", category: "not-plant" },
        { id: "chair", label: "Chair", emoji: "🪑", category: "not-plant" },
        { id: "sunflower", label: "Sunflower", emoji: "🌻", category: "plant" },
      ],
    },
  },
  {
    id: "plants-match",
    zoneId: "plants",
    type: "memory_match",
    title: "Plant & Fruit Match",
    description: "Match each plant with its fruit!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Flip the cards and find matching pairs!",
      pairs: [
        { id: "apple", front: "Apple Tree", emoji: "🍎" },
        { id: "banana", front: "Banana Plant", emoji: "🍌" },
        { id: "coconut", front: "Coconut Palm", emoji: "🥥" },
        { id: "orange", front: "Orange Tree", emoji: "🍊" },
        { id: "mango", front: "Mango Tree", emoji: "🥭" },
        { id: "grape", front: "Grape Vine", emoji: "🍇" },
      ],
    },
  },
  {
    id: "plants-sequence",
    zoneId: "plants",
    type: "sequence_builder",
    title: "Seed to Flower",
    description: "Put the steps of plant growth in order!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "Arrange the steps to show how a plant grows!",
      steps: [
        { id: "seed", label: "Plant a seed", emoji: "🫘", order: 1 },
        { id: "water", label: "Water it", emoji: "💧", order: 2 },
        { id: "sprout", label: "Sprout appears", emoji: "🌱", order: 3 },
        { id: "grow", label: "Stem grows tall", emoji: "🌿", order: 4 },
        { id: "bud", label: "Bud forms", emoji: "🌷", order: 5 },
        { id: "flower", label: "Flower blooms!", emoji: "🌸", order: 6 },
      ],
    },
  },
  {
    id: "plants-odd-garden",
    zoneId: "plants",
    type: "odd_one_out",
    title: "Odd Plant Out",
    description: "One doesn't belong — find it!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "All of these are alike except one. Find the odd one out!",
      rounds: [
        {
          id: "r1",
          category: "plants",
          items: [
            { id: "tree", label: "Tree", emoji: "🌳" },
            { id: "rose", label: "Rose", emoji: "🌹" },
            { id: "cactus", label: "Cactus", emoji: "🌵" },
            { id: "car", label: "Car", emoji: "🚗" },
            { id: "sunflower", label: "Sunflower", emoji: "🌻" },
          ],
          oddId: "car",
          explanation: "A car is a vehicle — it's not a plant!",
        },
        {
          id: "r2",
          category: "fruits",
          items: [
            { id: "apple", label: "Apple", emoji: "🍎" },
            { id: "banana", label: "Banana", emoji: "🍌" },
            { id: "mango", label: "Mango", emoji: "🥭" },
            { id: "rock", label: "Rock", emoji: "🪨" },
          ],
          oddId: "rock",
          explanation: "A rock doesn't grow on trees — it's not a fruit!",
        },
        {
          id: "r3",
          category: "plant parts",
          items: [
            { id: "leaf", label: "Leaf", emoji: "🍃" },
            { id: "stem", label: "Stem", emoji: "🌿" },
            { id: "root", label: "Root", emoji: "🌱" },
            { id: "shoe", label: "Shoe", emoji: "👟" },
            { id: "flower", label: "Flower", emoji: "🌸" },
          ],
          oddId: "shoe",
          explanation: "A shoe is something you wear — it's not part of a plant!",
        },
        {
          id: "r4",
          category: "things plants need",
          items: [
            { id: "water", label: "Water", emoji: "💧" },
            { id: "sun", label: "Sunlight", emoji: "☀️" },
            { id: "soil", label: "Soil", emoji: "🟤" },
            { id: "tv", label: "Television", emoji: "📺" },
          ],
          oddId: "tv",
          explanation: "Plants don't watch TV! They need water, sunlight, and soil to grow.",
        },
      ],
    },
  },
  {
    id: "plants-true-false",
    zoneId: "plants",
    type: "true_false",
    title: "Plant Facts: True or False?",
    description: "How much do you know about plants?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Read each fact about plants and decide!",
      questions: [
        { id: "tf1", statement: "Plants need water to grow", emoji: "💧", isTrue: true, explanation: "Yes! Without water, plants get thirsty and wilt." },
        { id: "tf2", statement: "Roots grow above the ground", emoji: "🌱", isTrue: false, explanation: "No! Roots grow underground to drink water from the soil." },
        { id: "tf3", statement: "Leaves use sunlight to make food", emoji: "🍃", isTrue: true, explanation: "Correct! Leaves are like tiny solar-powered kitchens!" },
        { id: "tf4", statement: "A cactus can live in the desert", emoji: "🌵", isTrue: true, explanation: "Yes! Cactuses store water inside so they survive hot deserts." },
        { id: "tf5", statement: "Flowers grow from ice cubes", emoji: "🧊", isTrue: false, explanation: "No way! Flowers grow from seeds planted in soil." },
      ],
    },
  },
  {
    id: "plants-color-flower",
    zoneId: "plants",
    type: "color_activity",
    title: "Color the Flower",
    description: "Paint each part of the flower the right color!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "color_activity",
      instruction: "Pick the correct color for each part of the flower!",
      palette: ["#ef4444", "#22c55e", "#a16207", "#fbbf24", "#ec4899"],
      regions: [
        { id: "petals", label: "🌸 Petals", correctColor: "#ec4899", path: "" },
        { id: "stem", label: "🌿 Stem", correctColor: "#22c55e", path: "" },
        { id: "center", label: "🟡 Center", correctColor: "#fbbf24", path: "" },
        { id: "soil", label: "🟤 Soil", correctColor: "#a16207", path: "" },
      ],
    },
  },
];
