import type { GameConfig } from "../../types";

export const shelterGames: GameConfig[] = [
  {
    id: "shelter-houses-quiz",
    zoneId: "shelter",
    type: "picture_quiz",
    title: "Types of Houses",
    description: "Homes look different around the world!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Which home matches the clue?",
      questions: [
        {
          id: "q1",
          question: "Which home is often made from mud or sticks in villages?",
          options: [
            { id: "igloo", label: "Igloo", emoji: "🧊" },
            { id: "hut", label: "Hut", emoji: "🛖" },
            { id: "skyscraper", label: "Skyscraper", emoji: "🏙️" },
            { id: "tent", label: "Tent", emoji: "⛺" },
          ],
          correctId: "hut",
          explanation: "A hut is a simple home, often built with local materials like wood or mud!",
        },
        {
          id: "q2",
          question: "Which home is made of snow blocks in very cold places?",
          options: [
            { id: "hut", label: "Hut", emoji: "🛖" },
            { id: "igloo", label: "Igloo", emoji: "🧊" },
            { id: "boat", label: "Boat house", emoji: "⛵" },
            { id: "castle", label: "Castle", emoji: "🏰" },
          ],
          correctId: "igloo",
          explanation: "Igloos keep people warm inside even when it is freezing outside!",
        },
        {
          id: "q3",
          question: "Many city families live in a tall building with many floors. What is it?",
          options: [
            { id: "tent", label: "Tent", emoji: "⛺" },
            { id: "apartment", label: "Apartment building", emoji: "🏢" },
            { id: "cave", label: "Cave", emoji: "🪨" },
            { id: "nest", label: "Bird nest", emoji: "🪺" },
          ],
          correctId: "apartment",
          explanation: "Apartments stack many homes up high so lots of people can live in one building!",
        },
        {
          id: "q4",
          question: "Which home can you fold up and carry for camping?",
          options: [
            { id: "brick", label: "Brick house", emoji: "🧱" },
            { id: "tent", label: "Tent", emoji: "⛺" },
            { id: "palace", label: "Palace", emoji: "🏛️" },
            { id: "barn", label: "Barn", emoji: "🌾" },
          ],
          correctId: "tent",
          explanation: "A tent is a portable shelter — perfect for adventures outdoors!",
        },
      ],
    },
  },
  {
    id: "shelter-build-sequence",
    zoneId: "shelter",
    type: "sequence_builder",
    title: "Build a House",
    description: "Put the steps to build a simple house in order!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "What happens first when people build a house?",
      steps: [
        { id: "plan", label: "Make a plan", emoji: "📐", order: 1 },
        { id: "foundation", label: "Dig foundation", emoji: "⛏️", order: 2 },
        { id: "walls", label: "Build walls", emoji: "🧱", order: 3 },
        { id: "roof", label: "Add the roof", emoji: "🏠", order: 4 },
        { id: "windows", label: "Put windows & door", emoji: "🚪", order: 5 },
        { id: "home", label: "Move in — it's home!", emoji: "❤️", order: 6 },
      ],
    },
  },
  {
    id: "shelter-animal-homes-match",
    zoneId: "shelter",
    type: "memory_match",
    title: "Animal Homes Match",
    description: "Match each animal with where it lives!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "memory_match",
      instruction: "Find pairs — animal and its cozy home!",
      pairs: [
        { id: "bird", front: "Bird", emoji: "🪺" },
        { id: "bee", front: "Bee", emoji: "🐝" },
        { id: "dog", front: "Dog", emoji: "🐕" },
        { id: "fish", front: "Fish", emoji: "🐠" },
        { id: "rabbit", front: "Rabbit", emoji: "🐰" },
        { id: "spider", front: "Spider", emoji: "🕷️" },
      ],
    },
  },
  {
    id: "shelter-odd-out",
    zoneId: "shelter",
    type: "odd_one_out",
    title: "Odd Home Out",
    description: "Which home doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong!",
      rounds: [
        { id: "r1", category: "homes for people", items: [{ id: "house", label: "House", emoji: "🏠" }, { id: "apartment", label: "Apartment", emoji: "🏢" }, { id: "hut", label: "Hut", emoji: "🛖" }, { id: "tree", label: "Tree", emoji: "🌳" }], oddId: "tree", explanation: "A tree is a plant — people don't usually live in trees!" },
        { id: "r2", category: "animal homes", items: [{ id: "nest", label: "Nest", emoji: "🪹" }, { id: "cave", label: "Cave", emoji: "🕳️" }, { id: "burrow", label: "Burrow", emoji: "🐰" }, { id: "car", label: "Car", emoji: "🚗" }], oddId: "car", explanation: "A car is for driving, not an animal home!" },
        { id: "r3", category: "things inside a house", items: [{ id: "bed", label: "Bed", emoji: "🛏️" }, { id: "table", label: "Table", emoji: "🪑" }, { id: "lamp", label: "Lamp", emoji: "💡" }, { id: "whale", label: "Whale", emoji: "🐋" }], oddId: "whale", explanation: "A whale lives in the ocean, not inside a house!" },
      ],
    },
  },
  {
    id: "shelter-true-false",
    zoneId: "shelter",
    type: "true_false",
    title: "Shelter Facts: True or False?",
    description: "Test what you know about homes!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this fact about homes true or false?",
      questions: [
        { id: "tf1", statement: "Birds live in nests", emoji: "🪹", isTrue: true, explanation: "Yes! Birds build nests to lay eggs and raise baby birds." },
        { id: "tf2", statement: "Fish live in houses", emoji: "🐟", isTrue: false, explanation: "No! Fish live in water — rivers, lakes, and oceans." },
        { id: "tf3", statement: "A roof keeps rain out of a house", emoji: "🏠", isTrue: true, explanation: "Correct! The roof protects us from rain and sun." },
        { id: "tf4", statement: "Igloos are made of ice", emoji: "🧊", isTrue: true, explanation: "Yes! In very cold places, people built homes from snow and ice." },
        { id: "tf5", statement: "Dogs live in aquariums", emoji: "🐕", isTrue: false, explanation: "No! Dogs live in houses or dog houses — aquariums are for fish!" },
      ],
    },
  },
];
