import type { GameConfig } from "../../types";

export const timeSpaceDirectionGames: GameConfig[] = [
  {
    id: "timespace-compass-rose",
    zoneId: "time-space-direction",
    type: "picture_quiz",
    title: "North, South, East, West",
    description: "Like naming the arms of a wind vane in your book.",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "N, S, E and W are the four main directions.",
      questions: [
        {
          id: "d1",
          question: "The letter N on a compass usually stands for…",
          options: [
            { id: "north", label: "North", emoji: "⬆️" },
            { id: "night", label: "Night", emoji: "🌙" },
            { id: "nest", label: "Nest", emoji: "🪺" },
            { id: "nose", label: "Nose", emoji: "👃" },
          ],
          correctId: "north",
          explanation: "N is North — toward the top of many maps.",
        },
        {
          id: "d2",
          question: "S usually stands for…",
          options: [
            { id: "sun", label: "Sun", emoji: "☀️" },
            { id: "south", label: "South", emoji: "⬇️" },
            { id: "sleep", label: "Sleep", emoji: "😴" },
            { id: "soap", label: "Soap", emoji: "🧼" },
          ],
          correctId: "south",
          explanation: "S is South — opposite to North.",
        },
        {
          id: "d3",
          question: "E and W stand for East and…",
          options: [
            { id: "window", label: "Window", emoji: "🪟" },
            { id: "west", label: "West", emoji: "⬅️" },
            { id: "water", label: "Water", emoji: "💧" },
            { id: "wheel", label: "Wheel", emoji: "🛞" },
          ],
          correctId: "west",
          explanation: "W is West — where the sun appears to set.",
        },
      ],
    },
  },
  {
    id: "timespace-clock-quiz",
    zoneId: "time-space-direction",
    type: "picture_quiz",
    title: "Read the Clock",
    description: "Practice telling time the simple way!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Think like the short hand on a clock!",
      questions: [
        {
          id: "q1",
          question: "The short hand points to 3 and the long hand points to 12. What time is it?",
          options: [
            { id: "three", label: "3 o'clock", emoji: "🕒" },
            { id: "twelve", label: "12 o'clock", emoji: "🕛" },
            { id: "six", label: "6 o'clock", emoji: "🕕" },
            { id: "nine", label: "9 o'clock", emoji: "🕘" },
          ],
          correctId: "three",
          explanation: "When the long hand is on 12, we say the hour the short hand shows — three!",
        },
        {
          id: "q2",
          question: "How many big numbers are on a normal clock face?",
          options: [
            { id: "ten", label: "Ten", emoji: "🔟" },
            { id: "twelve", label: "Twelve", emoji: "1️⃣2️⃣" },
            { id: "twenty", label: "Twenty", emoji: "2️⃣0️⃣" },
            { id: "five", label: "Five", emoji: "5️⃣" },
          ],
          correctId: "twelve",
          explanation: "A clock shows twelve hours going around in a circle!",
        },
        {
          id: "q3",
          question: "Which comes first in the day — morning or night?",
          options: [
            { id: "morning", label: "Morning starts the day", emoji: "🌅" },
            { id: "night-first", label: "Night is always first", emoji: "🌙" },
            { id: "same", label: "They are the same instant", emoji: "⚡" },
            { id: "lunch", label: "Lunch only", emoji: "🥪" },
          ],
          correctId: "morning",
          explanation: "After night sleep, morning wakes us up for a new day!",
        },
        {
          id: "q4",
          question: "What do we use to know when to get to school on time?",
          options: [
            { id: "clock", label: "Clock or watch", emoji: "⏰" },
            { id: "guess", label: "Only guessing", emoji: "🤷" },
            { id: "color", label: "Favorite color", emoji: "🎨" },
            { id: "shoes", label: "Shoe size", emoji: "👟" },
          ],
          correctId: "clock",
          explanation: "Clocks help families plan meals, school, and bedtime!",
        },
      ],
    },
  },
  {
    id: "timespace-left-right-quiz",
    zoneId: "time-space-direction",
    type: "picture_quiz",
    title: "Left or Right?",
    description: "Learn left, right, and where things are!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "picture_quiz",
      instruction: "Imagine you are standing the same way as the picture in your mind!",
      questions: [
        {
          id: "q1",
          question: "Hold up your hands. Which hand makes a small L with thumb and pointer? (Usually)",
          options: [
            { id: "left", label: "Left hand", emoji: "👈" },
            { id: "right", label: "Right hand", emoji: "👉" },
            { id: "both", label: "Both at once", emoji: "🙌" },
            { id: "feet", label: "Your feet", emoji: "🦶" },
          ],
          correctId: "left",
          explanation: "For many people, the left hand makes an L shape — a trick to remember!",
        },
        {
          id: "q2",
          question: "If you face forward, your right side is…",
          options: [
            { id: "right-side", label: "The side with your right hand", emoji: "➡️" },
            { id: "behind", label: "Always behind you", emoji: "🔙" },
            { id: "above", label: "Above your head only", emoji: "⬆️" },
            { id: "under", label: "Under the floor", emoji: "⬇️" },
          ],
          correctId: "right-side",
          explanation: "Right and left are from your own body's point of view!",
        },
        {
          id: "q3",
          question: "Something 'between' two toys is…",
          options: [
            { id: "middle", label: "In the middle of them", emoji: "↔️" },
            { id: "above-both", label: "Above both only", emoji: "☁️" },
            { id: "gone", label: "Nowhere", emoji: "🚫" },
            { id: "same", label: "On top of only one", emoji: "1️⃣" },
          ],
          correctId: "middle",
          explanation: "Between means in the space in the middle of two things!",
        },
        {
          id: "q4",
          question: "You are 'in front of' the door when…",
          options: [
            { id: "facing", label: "You face the door on the outside side", emoji: "🚪" },
            { id: "inside-wall", label: "You are inside the wall", emoji: "🧱" },
            { id: "roof", label: "You sit on the roof only", emoji: "🏠" },
            { id: "under-mat", label: "Under the mat", emoji: "🧹" },
          ],
          correctId: "facing",
          explanation: "In front of means the side you walk toward before opening!",
        },
      ],
    },
  },
  {
    id: "timespace-my-day-sequence",
    zoneId: "time-space-direction",
    type: "sequence_builder",
    title: "My Day",
    description: "From morning routine to bedtime — in order!",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "sequence_builder",
      instruction: "Build your day from wake-up to sweet dreams!",
      steps: [
        { id: "wake", label: "Wake up", emoji: "⏰", order: 1 },
        { id: "wash", label: "Wash up & get dressed", emoji: "🪥", order: 2 },
        { id: "breakfast", label: "Breakfast", emoji: "🥣", order: 3 },
        { id: "school", label: "School or playtime", emoji: "🎒", order: 4 },
        { id: "dinner", label: "Dinner & family time", emoji: "🍽️", order: 5 },
        { id: "bath-story", label: "Bath, pajamas, story", emoji: "🛁", order: 6 },
        { id: "sleep", label: "Lights out — good night!", emoji: "😴", order: 7 },
      ],
    },
  },
  {
    id: "tsd-odd-out",
    zoneId: "time-space-direction",
    type: "odd_one_out",
    title: "Odd Time Out",
    description: "Which one doesn't belong?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "odd_one_out",
      instruction: "Find the one that doesn't belong!",
      rounds: [
        { id: "r1", category: "times of the day", items: [{ id: "morning", label: "Morning", emoji: "🌅" }, { id: "afternoon", label: "Afternoon", emoji: "☀️" }, { id: "night", label: "Night", emoji: "🌙" }, { id: "pizza", label: "Pizza", emoji: "🍕" }], oddId: "pizza", explanation: "Pizza is food — it's not a time of day!" },
        { id: "r2", category: "directions", items: [{ id: "north", label: "North", emoji: "⬆️" }, { id: "south", label: "South", emoji: "⬇️" }, { id: "east", label: "East", emoji: "➡️" }, { id: "banana", label: "Banana", emoji: "🍌" }], oddId: "banana", explanation: "A banana is a fruit, not a direction!" },
        { id: "r3", category: "days of the week", items: [{ id: "monday", label: "Monday", emoji: "1️⃣" }, { id: "friday", label: "Friday", emoji: "5️⃣" }, { id: "sunday", label: "Sunday", emoji: "7️⃣" }, { id: "elephant", label: "Elephant", emoji: "🐘" }], oddId: "elephant", explanation: "An elephant is an animal, not a day of the week!" },
      ],
    },
  },
  {
    id: "tsd-true-false",
    zoneId: "time-space-direction",
    type: "true_false",
    title: "Time & Direction Facts",
    description: "True or false?",
    difficulty: 1,
    maxStars: 3,
    data: {
      type: "true_false",
      instruction: "Is this fact true or false?",
      questions: [
        { id: "tf1", statement: "A clock tells us the time", emoji: "🕐", isTrue: true, explanation: "Yes! Clocks show hours and minutes." },
        { id: "tf2", statement: "There are 8 days in a week", emoji: "📅", isTrue: false, explanation: "No! There are 7 days in a week." },
        { id: "tf3", statement: "The sun rises in the east", emoji: "🌅", isTrue: true, explanation: "Correct! The sun always rises in the east." },
        { id: "tf4", statement: "January comes after December", emoji: "❄️", isTrue: true, explanation: "Yes! January is the first month of the new year." },
      ],
    },
  },
];
